build: install CGAL library in Dockerfile
robotics-laboratory/truck pull request #103
Opened 2024-01-13 21:43 UTC by andrew-milko

2024-01-13 21:46 UTC, andrew-milko commented on Dockerfile
> +WORKDIR /usr/include
Мне нужно устанавить CGAL в директории `/usr/include`.

Командой `WORKDIR` я в эту директорию попадаю, но я не знаю, нужно ли после выполнения всех установочных команд возвращаться с помощью команды `WORKDIR` в исходную директорию?

2024-01-13 22:14 UTC, AndBondStyle requested changes

2024-01-13 22:14 UTC, AndBondStyle commented on Dockerfile
> +    && apt-get install -yq install libmpfr-dev
Кажется это лучше докинуть в общую стопку зависимостей? И еще посмотри как в других местах ставятся пакеты, там есть очистка кеша в конце

2024-01-13 22:14 UTC, AndBondStyle commented on Dockerfile
> +WORKDIR /usr/include
Нежелательно эту команду использовать, лучше просто копировать в нужное место или чейнить команды `cd` внутри блока `RUN`

2024-01-13 22:14 UTC, AndBondStyle commented on Dockerfile
> +    && make install \
Make разве не положит куда надо готовые файлы? И не надо ничего придумывать с WORKDIR

2024-01-13 22:14 UTC, AndBondStyle commented on Dockerfile
> +    && cd cgal-{CGAL_VERSION} && mkdir -p build && cd build \
Тут кажется опечатка около `CGAL_VERSION`, а вообще лучше в `tar` команде указать явно название директории, в которую распаковываешь

2024-01-13 22:14 UTC, AndBondStyle commented on Dockerfile
> +    && rm -rf /tmp/*
Удаляешь директорию в которую распаковывал архив?

2024-01-14 14:24 UTC, andrew-milko commented on Dockerfile
> +WORKDIR /usr/include
> Нежелательно эту команду использовать, лучше просто копировать в нужное место или чейнить команды `cd` внутри блока `RUN`

Да, я потыкал в эти команды, осознал, что юзать `WORKDIR` в данном случаем не нужно.

2024-01-14 14:25 UTC, andrew-milko commented on Dockerfile
> +    && cd cgal-{CGAL_VERSION} && mkdir -p build && cd build \
> И build директорию разве обязательно создавать? Нельзя просто из корня репы запустить cmake + make

Создавать директорию `build` не обязательно, не буду.

2024-01-14 14:25 UTC, andrew-milko commented on Dockerfile
> +    && rm -rf /tmp/*
> Удаляешь директорию в которую распаковывал архив?

Да.

2024-01-14 14:26 UTC, andrew-milko commented on Dockerfile
> +    && apt-get install -yq install libmpfr-dev
> Кажется это лучше докинуть в общую стопку зависимостей?

Логично. Добавил скачивание `libmprf-dev` в раздел `### INSTALL COMMON PKGS`.

2024-01-17 10:25 UTC, merged