Simple lidar simulation
robotics-laboratory/truck pull request #104
Opened 2024-01-15 01:43 UTC by Oleg-Olegovich

Добавлена генерация сообщения лидара.
Ranges вычисляются простым алгоритмом: перебираем все лучи, для каждого луча перебираем все отрезки.
Также реализованы вспомогательные фичи.

2024-02-04 21:33 UTC, dasimagin requested changes

2024-02-04 21:33 UTC, dasimagin commented on packages/simulator_2d/package.xml
> +  <depend>map</depend>
Сейчас это не на что не влияет, т.к. стандартные пакеты у нас предсобраны в контейнере, но вы забыли `sensor_msgs`.

2024-02-04 21:33 UTC, dasimagin commented on packages/simulator_2d/include/simulator_2d/simulator_engine.h
> +    geom::Segments obstacles_;
Хммм... пусть будет так, окей...

2024-02-04 21:33 UTC, dasimagin commented on packages/simulator_2d/src/truck_state.cpp
> +TruckState& TruckState::lidarRanges(std::vector<float>& lidar_ranges) {
Так НЕЛЬЗЯ делать, интерфейм подразумевает, что мы не завладеете объектом, а максимум его измените, ниже же вы делаете `move`. Если хотите и дальше мувать, то у вас есть два варианта:
1. `TruckState& lidarRanges(std::vector<float> lidar_ranges)`
2. `TruckState& lidarRanges(std::vector<float>&& lidar_ranges)`

2024-02-04 21:33 UTC, dasimagin commented on packages/simulator_2d/src/simulator_node.h
> +        } lidar_config;
Повторюсь, очень странно, что это не часть модели...

2024-02-04 21:33 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +}
Так, ну я не такой "наивный" алгоритм предлагал... идея такая, берем начало и конец отрезка, понимаем, какие лучше лучи нужно проверять, проверяем только их, для каждого луча обновляем, нашли ли мы более близкое пересечение. У вас уже совсем прямолинейный перебор.

2024-02-04 21:33 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +    geom::Ray current_ray(pose.pos, pose.dir + cache_.lidar_angle_min);
Не учтена трансформация `base <=> lidar`.

2024-02-04 21:37 UTC, Oleg-Olegovich commented on packages/geom/include/geom/ray.h
> +    Vec2& intersection, double precision) noexcept;
Лично мне проще писать и читать if (checkIntersection). Но это дискуссионный вопрос, и мне будет проще переписать на optional.

2024-02-04 21:38 UTC, Oleg-Olegovich commented on packages/geom/src/ray.cpp
> +    }
Я думаю что стоит расширять. Лучше зафиксировать чуть больше пересечений, чем чуть меньше - вопрос безопасности.

2024-02-04 21:39 UTC, Oleg-Olegovich commented on packages/geom/src/ray.cpp
> +bool checkIntersection(const Ray& ray, const Segment& segment,
Вы про документирующий комментарий к функции?

2024-02-04 21:44 UTC, Oleg-Olegovich commented on packages/simulator_2d/src/simulator_engine.cpp
> +}
Тогда надо придумать алгоритм, отсекающий лучи. Мне сейчас такая идея пришла в голову:
1. Перебираем отрезки.
2. Проводим 2 луча из лидара, через каждый из концов отрезка.
3. Вычисляем полярные углы этих лучей.
4. Перебираем все лучи лидара между ними.

2024-02-04 21:45 UTC, Oleg-Olegovich commented on packages/simulator_2d/src/simulator_engine.cpp
> +    geom::Ray current_ray(pose.pos, pose.dir + cache_.lidar_angle_min);
Да, потому что считается, что lidar находится строго в base. Где-то есть иная информация?

2024-02-04 21:54 UTC, Oleg-Olegovich commented on packages/geom/include/geom/segment.h
> +    Segment() : begin({0, 0}), end({0, 0}) {}
Мне он понадобился в методе Polygon::segments. Там я объявляю вектор отрезков:
```Segments segments(points.size());```

После чего заполняю его:
```
    segments[0].begin = {points.back().x, points.back().y};
    segments[0].end = {points[0].x, points[0].y};

    for (size_t i = 1; i < points.size(); ++i) {
        segments[i].begin = {points[i - 1].x, points[i - 1].y};
        segments[i].end = {points[i].x, points[i].y};
    }
```

При инициализации вектора создаётся N отрезков, причём вызываются их дефолтные конструкторы.

2024-02-04 21:56 UTC, Oleg-Olegovich commented on packages/geom/test/main.cpp
> +    ASSERT_GEOM_EQUAL(intersection, correct_intersection, precision);
Мне как раз не нравилось множественное дублирование кода. И конкретно здесь у меня тесты и падали, и проходили. Мне хватило информации для дебага.

2024-02-04 21:57 UTC, Oleg-Olegovich commented on packages/simulator_2d/config/lidar.json
> +    "range_max": 100.0
Чтобы можно было передавать симулятору разные конфигурации лидара без изменения модели.
Перенесу в модель.

2024-02-04 21:58 UTC, Oleg-Olegovich commented on packages/simulator_2d/package.xml
> +  <depend>map</depend>
Спасибо!

2024-02-04 22:13 UTC, dasimagin commented on packages/geom/include/geom/segment.h
> +    Segment() : begin({0, 0}), end({0, 0}) {}
А в чем проблема сделать reserve и просто пушить объекты? Просто дефолтный конструктор у отрезка странная штука...

2024-02-04 22:15 UTC, dasimagin commented on packages/geom/include/geom/ray.h
> +    Vec2& intersection, double precision) noexcept;
В целом есть два вариант это делать...

```
const auto result = GetIntersection();
if (!result) {
  return ...;
}

//...
```

И еще есть такая оция, но я ее меньше люблю

```
if (const auto result = GetIntersection(...); result) {
  // ...
}

return ...;
```

2024-02-04 22:16 UTC, dasimagin commented on packages/geom/src/ray.cpp
> +    }
Это просто еще библиотечная функция... ну, пусть будет так!

2024-02-04 22:16 UTC, dasimagin commented on packages/geom/test/main.cpp
> +    ASSERT_GEOM_EQUAL(intersection, correct_intersection, precision);
Для тестов норм )

2024-02-04 22:17 UTC, dasimagin commented on packages/simulator_2d/config/lidar.json
> +    "range_max": 100.0
Да как-то странно это все выглядит...

2024-02-04 22:20 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +    geom::Ray current_ray(pose.pos, pose.dir + cache_.lidar_angle_min);
Хранится все [тут](https://github.com/robotics-laboratory/truck/blob/master/packages/model/config/tf_static.yaml), вы же это прекрасно знаете. Лучше не закладываться, что это сейчас одно и то же.

2024-02-04 22:21 UTC, dasimagin commented on packages/geom/src/ray.cpp
> +bool checkIntersection(const Ray& ray, const Segment& segment,
Скорее прям в `.cpp` для читателей.

2024-02-22 03:20 UTC, dasimagin approved these changes

2024-02-22 03:20 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +            = getAngleBetween(origin, dir_vector, segment.end);
Это ориентированный угол обычно называется...

2024-02-22 03:20 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +        min_angle_rad = std::max(dir_angle_rad, min_angle_rad);
> `min_angle_rad = std::max(dir_angle_rad, min_angle_rad)`

что делает эта строчка?

2024-02-22 03:20 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +        for (size_t i = index; i < ranges.size() && current_ray.dir < max_angle; ++i) {
1. На `i < ranges.size()` скорее надо `VERIFY` поставить, если мы выйдем по этому условию, то это баг )
2. Опять же из-за плавающей точки вы тут можете неприятный момент словить и сделать лишний шаг, видимо, у вас это стреляло? Да, коль есть условия `i < ranges.size()`? Лучше, что вы можете сделать это просто явно найти истовые индексы для перебора и понимать в цикле и идти. Надежнее так сделать.

2024-02-22 03:20 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +        const int index = std::ceil((min_angle_rad - dir_angle_rad) / increment_rad);
имя путающее... назовите begin или типа того...

2024-02-22 03:20 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +        const auto max_angle = geom::AngleVec2(std::max(lidar_to_begin_angle, lidar_to_end_angle));
Обычно такое делаю через swap

```
if (min_v > max_x) {
  std::swap(min_v, max_v);
}
```

2024-02-22 08:09 UTC, Oleg-Olegovich commented on packages/simulator_2d/src/simulator_node.h
> +        rclcpp::Subscription<tf2_msgs::msg::TFMessage>::SharedPtr tf_static = nullptr;
Нет, никто это не решал. Надо поставить задачу по переносу в конфиг?

2024-02-22 08:09 UTC, Oleg-Olegovich commented on packages/simulator_2d/src/simulator_node.cpp
> +}
Просто брать из модели пока нельзя, потому что в модели этого нет.

2024-02-22 08:12 UTC, Oleg-Olegovich commented on packages/simulator_2d/src/simulator_engine.cpp
> +        min_angle_rad = std::max(dir_angle_rad, min_angle_rad);
Эта строчка берёт максимум из угла направления лидара и минимального угла отрезка. Это важно, если минимальный угол отрезка меньше направления лидара.

2024-02-22 08:13 UTC, Oleg-Olegovich commented on packages/simulator_2d/src/simulator_engine.cpp
> +        for (size_t i = index; i < ranges.size() && current_ray.dir < max_angle; ++i) {
Лишний шаг вряд ли был из-за второго условия:
`current_ray.dir < max_angle`
Но я согласен, зная max_angle, можно сразу посчитать последний индекс. Условие проще будет.

2024-02-24 21:51 UTC, merged