perf: switch collision from OpenCV to fastgrid
robotics-laboratory/truck pull request #121
Opened 2024-02-27 18:41 UTC by thenromanov

perf: make dynamic memory allocaion for collision_map

2024-03-04 01:32 UTC, dasimagin approved these changes
Ставлю ОК заранее, задав вопросы.

2024-03-04 01:32 UTC, dasimagin commented on packages/collision/src/collision_map.cpp
> +    }
Если я понял ваш код, то размер `bit_map_` равен `occupancy_grid`. Тогда зачем так сложно, сделайте просто `copy` массива?

2024-03-04 01:32 UTC, dasimagin commented on packages/collision/include/collision/collision_map.h
> +    } distance_map_;
В целом я не сильно понял, зачем так сложно... почему просто не сделать метод
```
void update(
    nav_msgs::msg::OccupancyGrid::ConstSharedPtr occupancy_grid,
    std::shared_ptr<const map::Map> map) noexcept;
```

Тогда не надо беспокоиться о консистентности ¯\_(ツ)_/¯

2024-03-04 01:32 UTC, dasimagin commented on packages/collision/include/collision/collision_map.h
> +    } distance_map_;
Отдельно отмечу, что хочется не полагаться только на размера грида... по какой-то причине может захотеться область меньше или больше. Подумайте, может быть лучше принимать позицию робота или `bbox` и, исходя из этого, вычислять матрицу занятости.

2024-03-04 01:32 UTC, dasimagin commented on packages/collision/include/collision/collision_checker.h
> +    void reset(const std::shared_ptr<CollisionMap> collision_map);
Странный интерфейс... либо делайте константную ссылку, либо принимайте по значению.

2024-03-04 01:32 UTC, dasimagin commented on packages/collision/src/collision_checker.cpp
> +    return interpolation.Get(point);
Давайте вынесем это в интерполяцию, сделайте метод, который принимает `default`.
```
T Get(const geom::Vec2& point, const T& def_val);
```

2024-03-04 01:32 UTC, dasimagin commented on packages/collision/src/collision_checker.cpp
> +    const auto [x, y] = interpolation.domain.Transform(point);
А у нас оси грида произвольно повернуты, да? Я просто вспоминаю...

2024-03-04 01:32 UTC, dasimagin commented on packages/fastgrid/src/draw.cpp
> +        input.push_back(cv::Point(floor<int>(point.x), floor<int>(point.y)));
А что мотивировало? Мне просто интересно... оно где-то не те клеточки красит, потому что делаем округление вверх?

2024-03-04 01:32 UTC, dasimagin commented on packages/planner/include/planner/planner_node.h
>      std::shared_ptr<collision::StaticCollisionChecker> checker_ = nullptr;
Не логично ли эту штуку сделать внутрянкой `StaticCollisionChecker`? Есть мотивация хранить по отдельносит?

2024-03-04 10:12 UTC, thenromanov commented on packages/fastgrid/src/draw.cpp
> +        input.push_back(cv::Point(floor<int>(point.x), floor<int>(point.y)));
Там внутри fillPoly с целыми координатами работает, а отрицательные даблы в int катятся как бы как округление вверх. Я сделал, чтобы явно вниз все округлялось.

2024-03-04 10:21 UTC, thenromanov commented on packages/collision/src/collision_map.cpp
> +    }
Насколько я понимаю, в `msg::OccupancyGrid` препятствия маркируют как "не 0". А в `fastgrid` у нас наоборот препятствия "0". Поэтому надо перекастовывать туда-обратно.
Но два фора да, наверняка можно это в какую-нибудь STL функцию закинуть.

2024-03-04 15:30 UTC, thenromanov commented on packages/collision/include/collision/collision_map.h
> +    } distance_map_;
> В целом я не сильно понял, зачем так сложно... почему просто не сделать метод
> 
> ```
> void update(
>     nav_msgs::msg::OccupancyGrid::ConstSharedPtr occupancy_grid,
>     std::shared_ptr<const map::Map> map) noexcept;
> ```
> 
> Тогда не надо беспокоиться о консистентности ¯_(ツ)_/¯

Вообще идея проверки консистентности растет не отсюда, а из того, что я хочу дорогие вычисления не в момент `update` делать, а непосредственно если просят `GetBitMap` или `GetDistanceMap`. Подумаю...

2024-03-04 16:07 UTC, thenromanov commented on packages/planner/include/planner/planner_node.h
>      std::shared_ptr<collision::StaticCollisionChecker> checker_ = nullptr;
До этого они хранились раздельно, а мне не хватало смелости так сильно перелопачивать чужие ноды. Подумаю...

2024-03-10 04:40 UTC, dasimagin commented on packages/collision/src/collision_map.cpp
> +    }
Ммм, нет у нас тоже препятствие должно быть больше нуля, если это не так, то давайте исправим это!

2024-03-10 04:41 UTC, dasimagin commented on packages/collision/include/collision/collision_map.h
> +    } distance_map_;
Да, так можно делать ленивые вычисления, но они нам нужны?

2024-03-10 04:42 UTC, dasimagin commented on packages/planner/include/planner/planner_node.h
>      std::shared_ptr<collision::StaticCollisionChecker> checker_ = nullptr;
Не стесняйтесь, надо сделать :)

2024-03-15 13:55 UTC, thenromanov commented on packages/collision/src/collision_map.cpp
> +    }
Исправил в #132

2024-03-15 14:19 UTC, thenromanov commented on packages/planner/include/planner/planner_node.h
>      std::shared_ptr<collision::StaticCollisionChecker> checker_ = nullptr;
🫡

2024-03-23 21:57 UTC, thenromanov commented on packages/planner/include/planner/planner_node.h
>      std::shared_ptr<collision::StaticCollisionChecker> checker_ = nullptr;
Объединил

2024-03-23 22:05 UTC, thenromanov commented on packages/collision/include/collision/collision_map.h
> +    } distance_map_;
> Отдельно отмечу, что хочется не полагаться только на размера грида... по какой-то причине может захотеться область меньше или больше. Подумайте, может быть лучше принимать позицию робота или `bbox` и, исходя из этого, вычислять матрицу занятости.

Сделал так: `collision_checker` в параметрах принимает радиус окрестности вокруг машинки и `resolution`. Затем в нем можно обновлять `occupancy_grid`, карту и текущее положение машинки. Грид берется в квадрате заданного радиуса вокруг текущего положения машинки. Оси грида строятся относительно мира машинки (`origin` берется как сдвиг на `radius` по `x` и `y` машинки, направление оси `x` грида берется как `ego_pose.dir.right()`).

> Да, так можно делать ленивые вычисления, а они нам нужны?

Немного переписав, оставил кэширование дорогих вычислений и пересчет только в момент запроса. Может это не обязательно, но делать дорогие вычисления реже точно хуже не будет.

2024-03-23 22:05 UTC, thenromanov commented on packages/collision/src/collision_checker.cpp
> +    return interpolation.Get(point);
Сделал

2024-03-23 22:06 UTC, thenromanov commented on packages/collision/src/collision_checker.cpp
> +    const auto [x, y] = interpolation.domain.Transform(point);
https://github.com/robotics-laboratory/truck/pull/121#discussion_r1536699073

2024-03-23 22:30 UTC, thenromanov commented on packages/collision/include/collision/collision_map.h
> +    } distance_map_;
> В целом я не сильно понял, зачем так сложно... почему просто не сделать метод
> 
> ```
> void update(
>     nav_msgs::msg::OccupancyGrid::ConstSharedPtr occupancy_grid,
>     std::shared_ptr<const map::Map> map) noexcept;
> ```
> 
> Тогда не надо беспокоиться о консистентности ¯_(ツ)_/¯

Еще забыл отметить: я явно хочу иметь возможность отдельно добавлять карту или `occupancy_grid`. Во-первых, текущие ноды, использующие `collision_checker` не поддерживают работу с картой, а кидать туда какую-нибудь болванку не хочется. Во-вторых, мне кажется удобным иметь возможность работать с `distance_transform`'ом на гриде без карты или на карте без грида.

2024-04-14 02:56 UTC, dasimagin requested changes

2024-04-14 02:56 UTC, dasimagin commented on packages/collision/include/collision/collision_checker.h
> +    } distance_map_cache_;
Я изучил этот код...
1) какую задачу это все решаете? Реально ли это все надо?
2) Зачем смешивать такую простую и прозрачную штуку, как `CollisionChecker` и бизнес логику заполнения финального грида занятости?

Если у нас появляется какая-то сложная логика формирования гридов, то почему бы не вынести это в отдельную операцию, а здесь использовать результат? Зачем делать комбайн?

Есть причина, из-за чего вся эта сложность может понадобиться, это если мы хотим передать в пользование `CollisionChecker` ДО того, как грид будет создан. Однако я слабо представляю, когда это может понадобиться.

2024-07-06 23:39 UTC, closed without merging