feat: add lidar_map package
robotics-laboratory/truck pull request #169
Opened 2024-06-09 16:32 UTC by apmilko

2024-06-09 19:13 UTC, apmilko commented on packages/lidar_map/include/lidar_map/serializer.h
> +        std::string odom = "/ekf/odometry/filtered";
Название топика, откуда берем одометрию.

2024-06-09 19:13 UTC, apmilko commented on packages/lidar_map/include/lidar_map/serializer.h
> +        std::string point_cloud = "/lidar/scan";
Название топика, откуда берем облака.

2024-06-09 19:17 UTC, apmilko commented on packages/lidar_map/src/builder.cpp
> +}  // namespace
Может все функции внутри безымянного `namespace`'а стоит вынести в хедер `common.h`?

2024-06-09 19:18 UTC, apmilko commented on packages/lidar_map/src/builder.cpp
> +            }
Мы не хотим строить ICP-ребра между вершинами, который находятся на расстоянии больше, чем `params_.icp_edge_max_dist`.

2024-06-27 09:47 UTC, apmilko commented on packages/lidar_map/example.md
> +Пример работы с библиотекой:
Файл `example.md` нужен, чтобы в рамках пиара показать пример работы с библиотекой. Потом я его удалю.

2024-07-02 13:08 UTC, apmilko commented on packages/lidar_map/test/main.cpp
> +    serializer.serializeToMCAP(lidar_map, "/lidar_map", vector_map, "/vector_map");
Получаем такой бэг:
![image_2024-07-02_15-42-31](https://github.com/robotics-laboratory/truck/assets/80720287/e257a63f-dc9b-4c41-aa5d-32fb40b01f43)

2024-07-02 13:12 UTC, apmilko commented on packages/lidar_map/test/main.cpp
> +        .bag_name = {.ride = "ride_sim_map_7_1", .cloud = "cloud_sim_map_7_1"}};
Отдельно стоит упоминуть иерархию библиотеки. Внутри пакета `lidar_map` есть стандартная папка `test`, внутри которой лежат:

- скрипт `main.cpp` для запуска тестов
- файл `CMakeLists.xtx`
- папка `bags`

В папке `bags` есть две подпапки:
- `rides`: бэги с проездами в реальности / в симулятор
- `clouds`: бэги с построенными лидарными картами

Иерархия проекта:
![image_2024-07-02_15-49-51](https://github.com/robotics-laboratory/truck/assets/80720287/5fc0c1ab-1238-4b84-9d10-72207ed17a65)

2024-07-02 13:17 UTC, apmilko commented on packages/lidar_map/src/serializer.cpp
> +const std::string RIDE_BAGS_FOLDER_PATH = "/truck/packages/lidar_map/test/bags/rides/";
Путь, по которому лежат бэги с проездами в симуляторе / в реальности.

2024-07-02 13:18 UTC, apmilko commented on packages/lidar_map/src/serializer.cpp
> +const std::string CLOUD_BAGS_FOLDER_PATH = "/truck/packages/lidar_map/test/bags/clouds/";
Путь, по которому лежат бэги с построенными лидарными картами.

2024-07-08 19:45 UTC, dasimagin requested changes

2024-07-08 19:45 UTC, dasimagin commented on packages/lidar_map/src/builder.cpp
> +    return transformationMatrixIn2D(tx, ty, dtheta);
Хм, у меня не так выходит... показывайте бумажку, как это было получено.

2024-07-08 19:45 UTC, dasimagin commented on packages/lidar_map/src/builder.cpp
> +g2o::SE2 toTransformationVector(const geom::Pose& pose) {
Хм, к сожалению, я не знаю, как эта штука устроена внутри... надо почитать.

2024-07-08 19:45 UTC, dasimagin commented on packages/lidar_map/src/builder.cpp
> +    VERIFY(poses.size() == clouds.size());
Это потенциальная намек, что раздельная схема хранения потенциально не самая лучшая...

2024-07-08 19:45 UTC, dasimagin commented on packages/lidar_map/src/builder.cpp
> +    }
Логичнее помещать точки в индекс, затем по индексу искать ближайшую и, если она достаточно далеко, делать добавление.

2024-07-08 19:45 UTC, dasimagin commented on packages/lidar_map/src/builder.cpp
> +        Eigen::Vector3f translation_vector = translationVectorIn3DFromPose(poses[i]);
https://eigen.tuxfamily.org/dox-3.2/group__Geometry__Module.html#title21, я бы скорее что-то такое тут ожидал...

2024-07-08 19:45 UTC, dasimagin commented on packages/lidar_map/src/builder.cpp
> +        }
Это же просто одно матричное умножение на матрицу трансформации, что за бред вы тут пишите?

2024-07-08 19:45 UTC, dasimagin commented on packages/lidar_map/src/builder.cpp
> +    }
Выглядит, как отделимая операция...

2024-07-08 19:45 UTC, dasimagin commented on packages/lidar_map/src/builder.cpp
> +        g2o::make_unique<BlockSolverType>(g2o::make_unique<LinearSolverType>()));
Сырой указатель?! Что за дичь тут вообще происходит... идите читать cppreference.

2024-07-08 19:45 UTC, dasimagin commented on packages/lidar_map/src/builder.cpp
> +        Eigen::Matrix3f tf_matrix_odom = transformationMatrixIn2DFromPoses(poses[i - 1], poses[i]);
Зачем тут нужен промежуточный объект? Словно бы `g2o::SE2` очень удобно устроено?

2024-07-08 19:45 UTC, dasimagin commented on packages/lidar_map/src/builder.cpp
> +        optimizer.addEdge(edge);
Оптимайзер потом умеет сам за собой чистить? Есть дока по этому поводу?

2024-07-08 19:45 UTC, dasimagin commented on packages/lidar_map/src/builder.cpp
> +            Cloud cloud_j_tf = Cloud(clouds[j]);
А просто конструктор копирования не вызывается что ли?

2024-07-08 19:45 UTC, dasimagin commented on packages/lidar_map/src/builder.cpp
> +    g2o::VertexSE2* fixed_vertex = dynamic_cast<g2o::VertexSE2*>(optimizer.vertex(0));
Зачем тут нужен каст?

2024-07-08 19:45 UTC, dasimagin commented on packages/lidar_map/src/builder.cpp
> +        g2o::VertexSE2* optimized_vertex = dynamic_cast<g2o::VertexSE2*>(optimizer.vertex(i));
Зачем тут каст?

2024-07-08 19:45 UTC, dasimagin commented on packages/lidar_map/src/builder.cpp
> +            optimized_poses.push_back(toPose(tf_vector));
В какой системе координат тут все возвращается?

2024-07-08 20:32 UTC, hexwhyzet commented on packages/lidar_map/src/builder.cpp
> +    g2o::VertexSE2* fixed_vertex = dynamic_cast<g2o::VertexSE2*>(optimizer.vertex(0));
https://github.com/RainerKuemmerle/g2o/blob/de5878061be6e1f541c9f065f73a4c27da922078/g2o/examples/tutorial_slam2d/tutorial_slam2d.cpp#L139

Вот пример от создателя либы, SparseOptimizer это потомок HyperGraph который работает с абстрактными Vertex, поэтому нам и нужен каст

2024-07-08 21:40 UTC, hexwhyzet commented on packages/lidar_map/src/builder.cpp
> +        optimizer.addEdge(edge);
https://github.com/RainerKuemmerle/g2o/blob/de5878061be6e1f541c9f065f73a4c27da922078/g2o/core/hyper_graph.cpp#L206 Да, он за собой чистит, SparseOptimizer наследуется от HyperGraph

2024-07-08 21:40 UTC, hexwhyzet commented on packages/lidar_map/src/builder.cpp
> +        g2o::VertexSE2* optimized_vertex = dynamic_cast<g2o::VertexSE2*>(optimizer.vertex(i));
https://github.com/robotics-laboratory/truck/pull/169/files/1f2d1f470682cc69aa3a800848ba6928e594576f#r1669273185

2024-07-08 21:40 UTC, hexwhyzet commented on packages/lidar_map/src/conversion.cpp
> +    Cloud result(feature_labels, descriptor_labels, point_count);
А зачем? feature_labels это матрица, ее размеренность можно узнать https://github.com/norlab-ulaval/libpointmatcher/blob/34ae751ecae46a970d30bd867aabc6b8b75bbebc/pointmatcher/DataPoints.cpp#L102

2024-07-08 21:40 UTC, hexwhyzet commented on packages/lidar_map/src/builder.cpp
> +        Eigen::Matrix3f tf_matrix_odom = transformationMatrixIn2DFromPoses(poses[i - 1], poses[i]);
В этом месте и правда можно сразу создать `g2o::SE2`, но в другом месте чуть ниже есть код который использует именно матрицу из transformationMatrixIn2DFromPoses

2024-07-16 11:04 UTC, apmilko commented on packages/lidar_map/src/builder.cpp
> +    return transformationMatrixIn2D(tx, ty, dtheta);
> Хм, у меня не так выходит... показывайте бумажку, как это было получено.

У меня все сошлось, ошибок в вычислениях нет, прикладываю [выкладки](https://drive.google.com/file/d/1ka1qI_AfBBuDj921c98vjKYnF-SRcqz6/view?usp=sharing). Использованные обозначения: `x_i = pose_i.pos.x`.

Формулу для обращения матрицы трансформации брал [отсюда](https://mecharithm.com/learning/lesson/homogenous-transformation-matrices-configurations-in-robotics-12).

Также пользовался формулами синусов и косинусов:
![Screenshot from 2024-07-16 13-43-33](https://github.com/user-attachments/assets/a28eec40-2300-48b1-9045-803940760cbe)

2024-07-16 14:26 UTC, apmilko commented on packages/lidar_map/src/builder.cpp
> +    matrix(1, 1) = std::cos(dtheta);
> Мне кажется или мы единицу потеряли?

Видимо вы про единицу в ячейке `matrix(2, 2)`, мы её не потеряли, т.к. `matrix` инициализируется как единичная матрица.

2024-07-17 13:24 UTC, apmilko commented on packages/lidar_map/src/conversion.cpp
> +    };
> А где у нас все цвета определены?

Цвета и их конвертация определены в пакете  `visualization`

> Не хотим конвертацию туда вынести один раз? Туда же и рисование многоугольника можно вынести...

Согласен, конвертацию цветов и рисование многоугольника нужно вынести в пакет, а именно в `visualization`. Внутри пакета `visualization` я создал библиотеку, которая состоит из уже существующего скрипта `src/color.cpp` (настройка цветов) и из нового скрипта `src/msg.cpp`, где я делаю конвератцию полигона в маркер.

2024-07-17 13:32 UTC, apmilko commented on packages/lidar_map/src/serializer.cpp
> +        writer->write(toMarker(*map), map_topic, get_timestamp());
> 1. Время тут не особо что-то значит, давайте просто ноль писать?

ОК.

> 2. Сделаем просто отдельно функцией?

Не понял, что имеется в виду.

2024-07-17 13:34 UTC, apmilko commented on packages/lidar_map/src/builder.cpp
> +    const auto segments = complex_polygon.segments();
> Тут копия происходит или что?

Копия, да. Такого не должно быть, исправил на `const auto& segments`.

2024-07-18 17:16 UTC, apmilko commented on packages/lidar_map/src/builder.cpp
> + */
> 1. А чего структуру не возвращаете? Еще бы и сразу комментик написали...

Исправил на структура, добавил комментарии.

> 2. Обычно пишут `q90`, `q95` и т.п. (то есть берем 90/95 первых ошибок и смотрим максимум.

ОК.

2024-07-19 09:42 UTC, apmilko commented on packages/lidar_map/include/lidar_map/serializer.h
> +};
> Хм, не уверен, что тут такая группировка органична...

От неё отказался, т.к. теперь нету класса `Serializer`, он разбит на отдельные функции.

2024-07-19 09:52 UTC, apmilko commented on packages/lidar_map/src/builder.cpp
> + */
> А зачем нужен `MSE`?

`MSE` я не добавлял, у меня есть `RMSE` и `mean`.

Иметь в качестве метрики качества только квантили не информативно, приведу пример.

Пусть у нас есть две лидарные карты, каждая состоит из `n` точек и у обоих карт метрика `q90 = 0.027`, то есть 90% точек имеют ошибку `<= 0.027m.`. Теперь представим, что в одной карте 90% точек имели ошибку строго равную `0.027m.`, а в другом 90% точек имели ошибку сильно меньше, чем `0.027m.`

В обоих случаях метрика `q90` будет одинаковая, она не дает нам информацию, какое из двух облаков лучше, а метрики `mean` и `RMSE` эту информацию нам мгут дать.

2024-07-19 09:52 UTC, apmilko commented on packages/lidar_map/src/builder.cpp
> + */
> Часть метрик еще не сделана... ¯_(ツ)_/¯

Добавил.

2024-07-19 09:55 UTC, apmilko commented on packages/lidar_map/src/builder.cpp
> +    };
> `std::accumulate` не подошел? Что у нас со знаком величин, которые сюда попадают?

Переписал на `std::accumulate`, с ним стало поприятнее. Что касается знака, то `value >= 0`.

2024-07-22 14:49 UTC, apmilko commented on packages/lidar_map/src/serializer.cpp
> +const std::string RIDE_BAGS_FOLDER_PATH = "/truck/packages/lidar_map/test/bags/rides/";
> Так, давайте уже не распротранять эту заразу по коду в абсолютными путями. Принимайте лучше через аргументы пути или предложите еще какие-то варианты.

Исправил, теперь указываю локальный путь.

2024-07-22 14:52 UTC, apmilko commented on packages/lidar_map/include/lidar_map/conversion.h
> +Cloud toCloud(const sensor_msgs::msg::LaserScan& scan, double z_lev = 1.0);
> 1. Я, кстати, задумался, хотим ли мы делать такую сильную завязку на `libpointmatcher` на уровне интерфейсов. Может просто `eigen` матрицу возвращать ...

Да, вы правы. На уровне интерфейсов облако пусть будет просто `eigen` матрицей, мне так тоже больше нарвится. Передалал. 

> 2. Я слабо представляю, когда в гомогенных координатах мы захоти НЕ единичку...

Согласен, парамет `z_lev` убрал.

2024-07-22 15:10 UTC, apmilko commented on packages/lidar_map/src/conversion.cpp
> +    Cloud result(feature_labels, descriptor_labels, point_count);
> Выглядит странно, а почему мы не выставляем размер `feature_labels`?

В этой функции `feature_labels` теперь вообще нет, т.к. `Cloud` теперь просто `eigen` матрица. 

Было:
```
using Cloud = Matcher::DataPoints;
```

Стало:
```
using Cloud = Eigen::Matrix3Xf;
```

2024-07-22 15:27 UTC, apmilko commented on packages/lidar_map/CMakeLists.txt
> +find_package(rclcpp REQUIRED)
> Зачем это нужно?

Убрал.

2024-07-22 15:27 UTC, apmilko commented on packages/lidar_map/package.xml
> +  <depend>rclcpp</depend>
> Зочем?

Убрал.

2024-07-22 15:46 UTC, apmilko commented on packages/lidar_map/src/builder.cpp
> +        const geom::Vec2 cloud_point = {cloud.features.col(i)(0), cloud.features.col(i)(1)};
> А у нас там единичка всегда п 3-й кординате?

Да.

2024-07-22 15:51 UTC, apmilko commented on packages/lidar_map/src/builder.cpp
> +}
> 1. МБ попроще будем делать?

Да, согласен. Я зарефакторил все-все свои функции для конвертации типов внутри `builder.cpp`, убрал лишнее и стало сильно приятнее.

2024-07-22 16:00 UTC, apmilko commented on packages/lidar_map/src/builder.cpp
> +}
> Хотя, вроде, нам достаточно одной матрицы трансформации?

Нам нужна только матрица трансформации. Отдельно вектор смещения или матрица поворота нам нигде не нужны.

2024-07-22 16:03 UTC, apmilko commented on packages/lidar_map/src/builder.cpp
> +    const geom::Pose& pose_i, const geom::Pose& pose_j) {
> Лучше писать from/to?

Я бы сделал так, но есть одна проблема. Над попределением функции я написал большой комментарий, описывающий принцип её работы и в обозначениях внутри описания фигурируют индексы `i, j`. Без индексов описание функции будет менее понятным.

Можем все-таки оставить `pose_i, pose_j`?

2024-07-22 16:05 UTC, apmilko commented on packages/lidar_map/src/builder.cpp
> +    }
> Выглядит, как отделимая операция...

Отделил.

2024-07-22 16:06 UTC, apmilko commented on packages/lidar_map/src/builder.cpp
> +            Cloud cloud_j_tf = Cloud(clouds[j]);
> А просто конструктор копирования не вызывается что ли?

Вызывается, исправил.

2024-07-22 16:12 UTC, apmilko commented on packages/lidar_map/src/builder.cpp
> +            optimized_poses.push_back(toPose(tf_vector));
> В какой системе координат тут все возвращается?

В мировой системе координат, то есть `optimized_poses[i]` - это оптимизированная поза фрейма, в котором мы знаем кординаты точек облака `clouds[i]`.

2024-07-23 11:44 UTC, apmilko commented on .gitignore
> +packages/lidar_map/data
В этой папке хранятся бэги с проездами и построенными картами.

2024-07-23 11:44 UTC, apmilko commented on packages/geom/src/distance.cpp
> +double distanceSq(const Vec2& p, const Segment& s) noexcept { return squared(distance(p, s)); }
Зарефакторил функцию нахождения расстояния от точки до отрезка. Кажется, что в ней были ошибки и ещё она была не очень понятно написана. Добавил реализацию `distance(Vec2, Segment)` помимо существующей `distanceSq(Vec2, Segment)`, написал тесты.

2024-07-23 11:44 UTC, apmilko commented on packages/lidar_map/README.md
> +# 2D Point Cloud Map Builder Library
Добавил `README.md` для библиотечки, расписал примеры работы с ней. Подскажите, что еще стоит дописать в текущую инструкцию?

2024-07-23 11:44 UTC, apmilko commented on packages/lidar_map/include/lidar_map/serializer.h
> +    std::vector<sensor_msgs::msg::LaserScan>& laser_scan_msgs);
Есть важный нюанс, что для корректной работы модуля построения карты нам недостаточно просто считать из бэга все сообщения одометрии и облаков. Во 1-ых, они должны быть попарно объединены и в идеале каждая пара должна иметь одинаковые `timestamp`ы, но сырые данные так не устроены.

В общем случае к нам прилетает `n` сообщений с облаками и `m` ссобщений с одометрией и их надо синхронизовать. Для модуля синхронизации важно, какой из топиков (облака или одометрия) публикуется чаще (у нас это одометрия).

Синхронизация работает так:
- слушаем очередное сообщение с облаком и запоминаем его `timestamp`: `cloud_ts`
- проходим слева-направо по всем сообщениям одометрии и ищем первое такое, что: `odom_ts` > `cloud_ts`
- запоминаем эту пару сообщений
- переходим к следующему сообщению с облаком
- повторяем алгоритм

Здесь очень важно подгонять именно одометрию к облакам, а не наоборот, иначе будет сильное расхождение по времени.

2024-07-23 11:44 UTC, apmilko commented on packages/lidar_map/include/lidar_map/serializer.h
> +    const geom::ComplexPolygon& map, const std::string& map_topic_name);
Когда мы собиарем карту по реальным данным, то векторную карту в бэг писать не нужно. Возможности дописывать топики в уже существующий бег у нас нет, поэтому для записи топиков в бэг было решено сделать две функции с перегрузкой.

2024-07-23 11:44 UTC, apmilko commented on packages/map/data/map_7.geojson
> +{
Добавил еще одну маленькую удобную карту, на ней удобно отлаживаться, все остальные слишком большие.

2024-07-23 11:44 UTC, apmilko commented on packages/lidar_map/CMakeLists.txt
> +add_executable(${PROJECT_NAME}_executable src/main.cpp)
Создал бинарик для построения карты, доабвил `README.md` с инструкцией к нему.

2024-07-24 09:48 UTC, apmilko commented on packages/geom/include/geom/angle_vector.h
> +    AngleVec2(double rad) : vec_(Vec2::fromAngle(Angle(rad))), angle_(Angle(rad)) {}
Мне не хватало такого конструктора.

2024-07-24 09:59 UTC, apmilko commented on packages/lidar_map/src/conversion.cpp
> +    auto is_valid = [&](double range) { return std::isnormal(range) && range_limit.isMet(range); };
> Верните проверку `isnan`.

`isnan` тут никогда не было, был `isfinite` (см. [комментарий](https://github.com/robotics-laboratory/truck/pull/166#discussion_r1650279354)), вернул на него.

2024-07-24 12:11 UTC, apmilko commented on packages/lidar_map/src/builder.cpp
> +}
> 2\. А нам точно нужно `3D`?

Не нужно, зарефакторил.

2024-07-24 12:52 UTC, apmilko commented on packages/lidar_map/src/builder.cpp
> +}
> 2. Вы же говорили, что все проверили? Я авторитетно утверждаю, что это не матрица поворота, она у вас не ортонормированная ¯_(ツ)_/¯

Здесь не согласен. Как эта матрица поворота (обозначим её за `R`) может быть не отнормирована, если я явно задаю в ней вс значения, в том числе и единички?

Я понимаю, если бы у нас была бы матрица поворота `R`, которая получилась из композиции других матриц поворота, то есть `R = R_1 * R_2 * ... * R_i`, тогда да, `R` стоит отнормировать, но у меня никакой композиции нету и я явно задаю всё значения, поэтому здесь нормировка не нужна. Разве не так?

2024-07-24 13:30 UTC, apmilko commented on packages/lidar_map/src/builder.cpp
> +        const geom::Vec2 cloud_point = {cloud.features.col(i)(0), cloud.features.col(i)(1)};
> нормировка надо делать?

Нормировку путем применения функции `Cloud normalize(const Cloud& cloud)` в нужных местах добавил.

2024-07-24 13:32 UTC, apmilko commented on packages/lidar_map/src/builder.cpp
> +        const geom::Vec2 cloud_point = {cloud.features.col(i)(0), cloud.features.col(i)(1)};
> А у нас там единичка всегда п 3-й кординате? нормировка надо делать?

По 3-ей координате должна быть единичка, но поскольку в коде мы к облакам применяем трансформации, то это не гарантируется. Поэтому нормировку действительно нужно делать, добавил её.

> Вы же понимаете, что там гомогенные координаты?

Да.

2024-07-24 13:33 UTC, apmilko commented on packages/lidar_map/src/builder.cpp
> +        }
> Да, у нас сейчас очень жиденькие полигончики... но в идеале тут бы по индексу находить сегмент, с которым хотим пересечься ¯_(ツ)_/¯
> 
> Там правда есть нюанс, что появляется верхний порог ошибки... (мы не можем замерить расстояние больше, чем сторона `bbox`-а, но это в целом и норм. Просто возьмите метр и все.

Можем оставить эту оптимизацию на потом? Мы карту же в оффлайн считаем, поэтому если это будет немного медленнее, чем могло бы быть, то нам это не критично же.

2024-07-25 07:45 UTC, apmilko commented on packages/lidar_map/src/builder.cpp
> +    }
> Логичнее помещать точки в индекс, затем по индексу искать ближайшую и, если она достаточно далеко, делать добавление.

Порефлексировал над этим, согласен. Мой алгоритм плох тем, что в местах loop-closure он не удалит близкие к друг другу позы, а ваше решение это учитывает. Исправил.

2024-07-26 15:03 UTC, apmilko commented on packages/lidar_map/src/builder.cpp
> +        }
> Да, у нас сейчас очень жиденькие полигончики... но в идеале тут бы по индексу находить сегмент, с которым хотим пересечься ¯_(ツ)_/¯
> 
> Там правда есть нюанс, что появляется верхний порог ошибки... (мы не можем замерить расстояние больше, чем сторона `bbox`-а, но это в целом и норм. Просто возьмите метр и все.

Я попробовал это реализовать и мне не понравилось, что при реализации через индексы получаемые значения метрик отличаются от идеальных (посчитанных втупую как у меня) ~ на 1 метр.

Мне кажется, что значения метрик у нас все-таки должны считаться без всяких погрешностей. Тем более подсчет метрик делаем всего 1 раз, поэтому скорость работы не так важна.

Если можно, я бы оставил свою реализацию.

2024-07-26 15:21 UTC, apmilko commented on packages/lidar_map/src/icp.cpp
> +}
По правде говоря, для конфигурации `ICP` нам не нужен отдельный класс `ICPBuilder`. В `lipbointmatcher`'е объект `ICP` можно легко собирать через `yaml` файлы, используя готовую функцию `ICP::loadFromYAML()`. Например, именно так вы и делаете в пакете `icp_odometry`.

Но я пока что не внедрил эту идею сюда, т.к. пока что ловлю баги при конфигурации `ICP` через `yaml` конфиг, пока не разобрался в чем дело.

Поэтому сделал временный базовый конфиг `buildBaseICP()`

2024-08-02 15:41 UTC, apmilko commented on packages/lidar_map/include/lidar_map/icp.h
> +struct ICPBuilderParams {};
> М? )

Класс `ICPBuilder` оказался вовсе ненужным, теперь я конфигурирую `ICP` через ланч файл `config.icp.yaml`

2024-08-02 15:42 UTC, apmilko commented on packages/lidar_map/src/icp.cpp
> +}
> М? )

Класс `ICPBuilder` оказался вовсе ненужным, теперь я конфигурирую `ICP` через ланч файл `config.icp.yaml`

2024-08-02 18:12 UTC, dasimagin commented on packages/geom/include/geom/angle_vector.h
> +    AngleVec2(double rad) : vec_(Vec2::fromAngle(Angle(rad))), angle_(Angle(rad)) {}
Хм... ну не знаю. Меня всегда в таких штуках беспокоит, что мы теряем знание о единицах измерения. Если хотите такую функциональность, то сделайте `AngleVec2::FromRadians(double rad)`, а конструктор `Angle(double rad)` лучше вообще сделать приватным, чтобы можно было использовать только в рамках класса.

2024-08-02 18:12 UTC, dasimagin commented on packages/geom/include/geom/msg.h
> +Poses toPoses(const std::vector<nav_msgs::msg::Odometry>& odom_msgs);
Видится, что это какая-то частность... лучше такое сюда не тащить.

2024-08-02 18:12 UTC, dasimagin commented on packages/geom/src/distance.cpp
> +double distanceSq(const Vec2& p, const Segment& s) noexcept { return squared(distance(p, s)); }
1. А вы понимаете почему вы заводим всегда версии `distanceSq` и `distace`? 
2. На каком тесте падает текущий код?

2024-08-19 04:36 UTC, dasimagin approved these changes

2024-08-19 04:36 UTC, dasimagin commented on packages/lidar_map/src/builder.cpp
> +        const double scalar = cloud.col(i)(2);
Это не логично... если у вас матрица в `float32`, но написав такой кож вы сделаете две конвертации: `float -> double`, а затем `double -> float`.

**P.S.** Работает и для функции ниже.

2024-08-19 04:36 UTC, dasimagin commented on packages/lidar_map/src/builder.cpp
> +}
Не думали тут использовать функцию выше? Собственно в комментарии вы уже все сами написали )

```
return T_iw * T_jw.inv();
```

2024-08-19 04:36 UTC, dasimagin commented on packages/lidar_map/src/builder.cpp
> +Builder::Builder(const BuilderParams& params, const ICP& icp) : icp_(icp), params_(params) {}
А зачем мы `ICP] именно так получаем?

2024-08-19 04:36 UTC, dasimagin commented on packages/lidar_map/src/builder.cpp
> +    VERIFY(poses.size() == clouds.size());
М?

2024-08-19 04:36 UTC, dasimagin commented on packages/lidar_map/src/builder.cpp
> +    rtree.insert(poses[0].pos);
Не сильно понял, зачем это надо...

2024-08-19 04:36 UTC, dasimagin commented on packages/lidar_map/src/main.cpp
> +        po::options_description desc("Options and arguments");
Ну, Андрей... тут пишут описание тулы )))

2024-08-19 04:36 UTC, dasimagin commented on packages/lidar_map/src/main.cpp
> +            }
А зачем все это? Разве бусы за вас это не делает? Вы точно хорошо доку почитали и примеры посмотрели?

2024-08-19 04:36 UTC, dasimagin commented on packages/lidar_map/src/main.cpp
> +            .verbose = false};
Если у вас есть желание, это можно тоже в параметры тулы вынести (для удобства можно определить дефолты).

2024-08-19 04:36 UTC, dasimagin commented on packages/lidar_map/src/main.cpp
> +        Builder builder = Builder(builder_params, icp);
Так а почему в итоге не внутри ICP создаем?

2024-08-20 14:05 UTC, merged