EKF odometry and sensor noise for 2D simulator
robotics-laboratory/truck pull request #172
Opened 2024-07-02 14:40 UTC by apmilko

2024-07-02 14:52 UTC, apmilko commented on packages/truck/launch/slam.yaml
> +    - { name: "publish_tf", value: "$(var publish_tf)" }
...

2024-07-02 14:53 UTC, apmilko commented on packages/truck/launch/slam.yaml
> +- let: { name: "publish_tf", value: "true", unless: "$(var simulation)" }
см. [комментарий](https://github.com/robotics-laboratory/truck/pull/172/files#r1662689625)

2024-07-02 15:00 UTC, apmilko commented on packages/simulator_2d/src/simulator_engine.cpp
>      cache_.base_to_hyro_rotation.setRotation(imu_tf.getRotation());
Переменная `tf2::Transform cache_.base_to_hyro_rotation` состоит из смещения и поворота. Поворот мы назначаем в 87-ой строчке, а смещение никакой не указываем, т.к. оно нам не нужно. Но если в смещении принудительно не проставить нули, то там будет мусор. Именно поэтому и нужна 86-ая строчка.

2024-07-03 15:23 UTC, apmilko commented on packages/truck/launch/slam.yaml
> +    - { name: "initial_state", value: [
Пользуемся аргументом [initial_state](https://docs.ros.org/en/noetic/api/robot_localization/html/state_estimation_nodes.html?highlight=frequency#initial-state).

2024-07-03 15:32 UTC, apmilko commented on packages/simulator_2d/CMakeLists.txt
> -
Удаляем файл папку `config` и лежащий в ней файлик `initial_ego_state.json`.

2024-07-03 15:51 UTC, apmilko commented on packages/simulator_2d/config/initial_ego_state.json
> -    "linear_velocity": 0.0
Не уверен, нужно ли включать в начальное состояние одометрии параметр `linear_velocity`, конфиг `slam.yaml` позволяет это делать.

Что касается парметра `middle_steering`, то в конфиге `slam.yaml` у нас нету возможности задавать начальный угол поворота колёс, поэтому парметр `middle_steering` в начальное состояние одометрии не включаем.

2024-07-03 17:00 UTC, apmilko commented on packages/simulator_2d/launch/simulator_pipeline.yaml
> +- arg: { name: "initial_y", default: "4.0" }
Значения аргументов по умолчанию именно такие, потому что иначе робот будет спавниться вне выставленной в конфиге карты.

2024-07-03 17:01 UTC, apmilko commented on packages/simulator_2d/src/simulator_node.cpp
> +    engine_->resetBase(pose, 0.0, 0.0);
Ставим `steering`, `velocity` по умолчанию нулевыми.

2024-07-03 17:02 UTC, apmilko commented on packages/simulator_2d/src/simulator_node.cpp
> +    pose.pos = geom::Vec2{x, y};
Кажется логичным задавать начальное состояние робота через центра, а не заднюю ось.

2024-07-04 19:58 UTC, dasimagin requested changes

2024-07-04 19:58 UTC, dasimagin commented on packages/hardware_node/hardware_node/node.py
> +            "/hardware/odometry",
Можно дать даже больше контекста в названии... `/hardware/wheel/odometry`.

2024-07-04 19:58 UTC, dasimagin commented on packages/simulator_2d/CMakeLists.txt
> -
Хм, ну ок...

2024-07-04 19:58 UTC, dasimagin commented on packages/truck_gazebo_plugins/src/motor_odometry.cpp
> +    slot_.odometry = node_->create_publisher<nav_msgs::msg::Odometry>("/hardware/odometry", 1);
Давайте уже тут удалим gazebo? B образе его потом можно выкорчевать... модели для справочной информации пока еще можно оставить :)

2024-07-04 19:58 UTC, dasimagin commented on packages/truck/launch/slam.yaml
> +    - { name: "initial_state", value: [
Так а вот это я не понял... почему тут просто нулей недостаточно? Обычно так поступают ¯\_(ツ)_/¯ но не надо путать это с глобальными координатами в симуляторе! Их мы хотим уметь задавать. Понимаете разницу?

2024-07-04 19:58 UTC, dasimagin commented on packages/truck/launch/slam.yaml
> +    - { name: "publish_tf", value: "$(var publish_tf)" }
Ну мы же не так договаривались... 
1. В симуляторе одометрия все равно должна быть включена всегда, она публикует в условный `/localization/ekf/odometry`. А у вас?
2. Симулятор же публикует истинную одометрию робота в условный `/simulation/odometry`, так же он может публиковать свою истинную трансформацию, но  просто с другим названием фрейма `odom_gt`, к примеру...

2024-07-04 19:58 UTC, dasimagin commented on packages/simulator_2d/include/simulator_2d/simulator_engine.h
> +    std::normal_distribution<double> lidar_dist_;
На мою память это медленная штука, а мы уже много вызовов будем делать... но можно пока оставить.

2024-07-04 19:58 UTC, dasimagin commented on packages/simulator_2d/include/simulator_2d/simulator_engine.h
> +    std::unique_ptr<NoiseGenerator> noise_generator_ = nullptr;
Хм, пусть пока так будет, мб потом зарефакторим.

2024-07-04 19:58 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +        gyro.x = gyro.x + gyro_dist_(generator_);
`+=`?

2024-07-04 19:58 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +    if (params_.gyro.enable) {
```
if (!params_.gyro.enable) {
  return;
}

//bla-bla-bla
```

2024-07-04 19:58 UTC, dasimagin commented on packages/simulator_2d/launch/simulator_pipeline.yaml
> +- arg: { name: "initial_y", default: "4.0" }
Давайте этот конфиг уже положим вместо газебы в `truck`...

2024-07-16 12:26 UTC, apmilko reviewed
В этом пиаре мы пока что не включаем EKF-фильтр в ланч-файл симулятора, т.к. просто EKF-фильтр нам не интересен, он интересен в тандеме с ICP-трансформацией между облаком машинки и облаком карты, которая будет вычисляться в ноде локализации `map_localization`.

Отдельным пиаром я создам ноду локализации, которая будет слушать топик `/ekf/odometry` с положением машинки (фрейма `base`) в фрейме `odom_ekf`. Затем мы уточним через ICP-трансформацию положение фрейма `world`  относительно фрейма `odom_ekf`. Задача ноды локализации публиковать трансформацию между фреймами `odom_ekf` и `world`.

2024-07-27 23:02 UTC, dasimagin requested changes

2024-07-27 23:02 UTC, dasimagin commented on packages/simulator_2d/src/simulator_node.cpp
> +    telemetry_msg.header.frame_id = "base_gt";
Почему не принципиально? Это же симуляция реальности, а там будет `base`...

2024-07-27 23:02 UTC, dasimagin commented on packages/simulator_2d/src/simulator_node.cpp
> +    msg.child_frame_id = "base_gt";
Это все прекрасно, но сейчас вы так разломаете визуализацию карты в симуляторе. Такой переход можно делать только после включения мировой локализации...

2024-07-28 13:05 UTC, apmilko commented on packages/simulator_2d/launch/simulator_2d.yaml
>    - arg:
Удалил вырожденный конфиг, которого не существует.

2024-07-28 13:05 UTC, apmilko commented on packages/truck/launch/simulator.yaml
> +    - { name: "map_config", value: "$(var map_config)" }
Аргумент `map_config` нужен для пакета `visualization`, который запускается внутри конфига `common.yaml`.

2024-07-28 13:05 UTC, apmilko commented on packages/truck/launch/common.yaml
> +    file: $(find-pkg-share truck)/launch/slam.yaml
Пакета `slam` у нас нет, конфиг `slam.yaml` находится в пакете `truck`. Еще я не понял, зачем нам писать условие `unless: "$(var simulation)"`? Кажется, что EKF-фильтр мы всегда хотим иметь включенным и в реальности, и в симуляторе.

2024-07-28 13:07 UTC, apmilko commented on packages/simulator_2d/src/simulator_node.cpp
> +    telemetry_msg.header.frame_id = "base_gt";
> Почему не принципиально? Это же симуляция реальности, а там будет `base`...

Согласен, исправил.

2024-07-28 15:53 UTC, dasimagin commented on packages/truck/launch/common.yaml
> +    file: $(find-pkg-share truck)/launch/slam.yaml
Нужно понимать, что кодовая база не высечена в камне. И мы будем периодически выставлять шорт-карты, чтобы как-то работать фейкая в симуляторе часть функциональности. Это скорее всего последствие того, что мы в симуляторе не хотели запускать `slam`, но сейчас и правда это условие можно убрать.

2024-07-28 15:58 UTC, dasimagin commented on packages/simulator_2d/src/simulator_node.cpp
> +    msg.child_frame_id = "base_gt";
Просто публикуйте пока base->world и все... а, когда добавите локализацию, то начнете добавим `base_gt`.

2024-07-28 16:00 UTC, dasimagin commented on packages/truck/launch/simulator.yaml
> +- arg: { name: "initial_yaw", default: "0.0" }
Если вы хотите запускать симуляцию из 10 разных мест, то, имхо удобнее 10 файлов иметь, чем десять лончей создавать или менять аргументы на лету. Но мне не принципиально, это не сложно переделать.

2024-07-28 16:01 UTC, dasimagin approved these changes

2024-07-30 15:24 UTC, merged