Integration with boost::geometry concepts
robotics-laboratory/truck pull request #175
Opened 2024-07-08 12:10 UTC by funham

2024-07-08 12:18 UTC, funham commented
Не запустил pre-commit

2024-07-08 14:42 UTC, apmilko commented on .gitignore
> +packages/geom_test
Что ты делаешь в пакете `geom_test` и почему он попал в `.gitignore`?

P.S.: в `.gitgnore` лежат директории, куда сохраняются результаты тестов какого-то пакета, которые мы не хотим хранить в нашем репозитории.

2024-07-08 14:47 UTC, apmilko commented on .gitignore
> +packages/geom_test
> Что ты делаешь в пакете `geom_test` и почему он попал в `.gitignore`?
> 
> P.S.: в `.gitgnore` лежат директории, куда сохраняются результаты тестов какого-то пакета, которые мы не хотим хранить в нашем репозитории.

Подозреваю, что в пакете `geom_test` ты проверял корректность работы регистрации типов. Кажется, что эти тесты нужно добавить в репозиторий в виде красивого скриптика `boost_tests.cpp`, котрый будет лежать в папке `packages/geom/test/*`.

Как нужно писать тесты посмотри на уже существующих [примерах](https://github.com/robotics-laboratory/truck/tree/xs1nus-geometry-boost-integration/packages/geom/test).

2024-07-08 14:52 UTC, funham commented on .gitignore
> +packages/geom_test
удалить пакет и запушить?

2024-07-08 14:53 UTC, apmilko commented on .gitignore
> +packages/geom_test
> удалить пакет и запушить?

Сначала ответь на вопросы)

2024-07-08 15:02 UTC, funham commented on .gitignore
> +packages/geom_test
Он был нужен чтобы просто проверить, будет ли компилироваться эта регистрация и проверить пару алгоритмов. Правда, я уже удалил все эти тесты (если их так можно назвать). Я изначально, на самом деле хотел сделать красивые тестики, но я не очень умею с ними работать и мне показалось, что проще было бы создать вспомогательный пакет.

2024-07-08 15:05 UTC, apmilko commented on .gitignore
> +packages/geom_test
> Он был нужен чтобы просто проверить, будет ли компилироваться эта регистрация и проверить пару алгоритмов. Правда, я уже удалил все эти тесты (если их так можно назвать). Я изначально, на самом деле хотел сделать красивые тестики, но я не очень умею с ними работать и мне показалось, что проще было бы создать вспомогательный пакет.

Думаю, что @dasimagin согласится со мной, что тесты на регистрацию типов все-таки не помешали, как минимум, из среди этих тестов можно будет найти примеры, как корректно использовать регистрацию типов. 
Выше я написал, где и как мы пишем тесты.

2024-07-08 15:08 UTC, funham commented on .gitignore
> +packages/geom_test
Хорошо. Тогда мне удалить лишний пакет (в т.ч. с gitignore), сделать пару тестиков и запушить?

2024-07-08 15:10 UTC, apmilko commented on .gitignore
> +packages/geom_test
Из `.gitignore` удалить, да. Тестики сделай, но не "пару", а на каждый зарегестрированный тип. Если ты зарегестрировал `k` типов, то и тестов должно быть не меньше, чем `k` штук. Может даже и больше, это смотря как тесты напишешь.

2024-07-08 15:13 UTC, apmilko commented on .gitignore
> +packages/geom_test
> Из `.gitignore` удалить, да. Тестики сделай, но не "пару", а на каждый зарегестрированный тип. Если ты зарегестрировал `k` типов, то и тестов должно быть не меньше, чем `k` штук. Может даже и больше, это смотря как тесты напишешь.

Но скрипт должен быть один: `boost_tests.cpp`

2024-07-08 16:04 UTC, dasimagin commented on packages/navigation/src/graph_builder.cpp
>  using RTreeBox = bg::model::box<RTreePoint>;
1. Почему не наш `box`?
2. Давайте лучше уберем алиас для `Vec2` и лучше сделаем `IndexPoint = std::pair<geom::Vec2, size_t>`

2024-07-08 16:04 UTC, dasimagin commented on packages/simulator_2d/include/simulator_2d/simulation_map.h
> +using RTreeSegment = geom::Segment;
Давайте не делать такие алиасы...

2024-07-09 07:51 UTC, apmilko commented on packages/geom/test/boost_tests.cpp
> +TEST(BoostSegment, bruh) {
`bruh`?

2024-07-09 07:56 UTC, apmilko requested changes
В тестах всё, что можно сделать `const`, должно быть `const`. [Пример](https://github.com/robotics-laboratory/truck/blob/master/packages/geom/test/arc_tests.cpp).

2024-07-09 08:01 UTC, apmilko commented on packages/routing/include/routing/routing_node.h
> +using RTreePoint = geom::Vec2;
Удалить.

2024-07-09 08:01 UTC, apmilko commented on packages/routing/include/routing/routing_node.h
>  using RTreeIndexedPoint = std::pair<RTreePoint, size_t>;
`using RTreeIndexedPoint = std::pair<geom::Vec2, size_t>;`

2024-07-09 08:04 UTC, apmilko commented on packages/geom/include/geom/boost/polygon.h
> +}  // namespace traits
Между 48 и 49 строчек нужно вставить пустую строку.

2024-07-09 08:11 UTC, apmilko commented on packages/navigation/src/graph_builder.cpp
> +using RTreeBox = geom::BoundingBox;
`using RTreeBox = geom::BoundingBox` нужно удалить по той же причине, почему ты удалил `using RTreePoint = bg::model::point<double, 2, bg::cs::cartesian>`.

Согласен?

2024-07-09 09:06 UTC, funham commented on packages/navigation/src/graph_builder.cpp
> +using RTreeBox = geom::BoundingBox;
Полностью согласен. Все вроде поправил. Постараюсь больше не коммитить ночью xD

2024-07-09 09:30 UTC, apmilko commented on packages/geom/test/boost_tests.cpp
> +    double y1 = bg::get<1, 1>(seg);
Почему не `const`?

2024-07-09 09:32 UTC, apmilko commented on packages/navigation/src/graph_builder.cpp
> +using RTreeBox = geom::BoundingBox;
> Полностью согласен. Все вроде поправил. Постараюсь больше не коммитить ночью xD

Спасибо за исправления, но нужно еще доделать:

1. Не убрал лишние строчки из `.gitignore`
2. Нужно переименовать `RTreeIndexedPoint` в `IndexPoint`, писали про это ([здесь](https://github.com/robotics-laboratory/truck/pull/175#discussion_r1668913623)). Сделай аналогичное переименование из `RTreeIndexedSegment` в `IndexSegment` и не забудь обновить названия для множественного числа: `IndexPoints` и `IndexSegements`
3. ты добавил `const` не везде, почему-то забыл про переменные типа `double`

2024-07-09 09:56 UTC, funham commented on packages/navigation/src/graph_builder.cpp
> +using RTreeBox = geom::BoundingBox;
1. Мне кажется, что у меня откатилась часть изменений каким-то образом, я точно помню что делал это...
2. Окей, неправильно понял
3. А double-то зачем const делать? Мы же его не тестируем...

2024-07-09 09:58 UTC, apmilko commented on packages/navigation/src/graph_builder.cpp
> +using RTreeBox = geom::BoundingBox;
> 3\. А double-то зачем const делать? Мы же его не тестируем...

Все переменные, которые в коде не меняются, должны быть `const`.

2024-07-09 13:16 UTC, apmilko commented on packages/geom/test/boost_tests.cpp
> +    const const double l = bg::length(ls);
`const const`? Зачем их два? Зачем их два?)

2024-07-09 13:23 UTC, apmilko requested changes

2024-07-09 13:23 UTC, apmilko commented on packages/geom/test/boost_tests.cpp
> +    const const double l = bg::length(ls);
`const const`? Зачем два? Зачем два?))

2024-07-09 13:23 UTC, apmilko commented on packages/navigation/include/navigation/graph_builder.h
> +#include "geom/boost/point.h"
Лишний инклюд, он уже есть в `graph_builder.cpp`

2024-07-09 13:23 UTC, apmilko commented on packages/simulator_2d/src/simulation_map.cpp
> +    std::vector<IndexSegment> result;
`std::vector<IndexSegment> result` заменить на `IndexSegments result`.

2024-07-09 16:26 UTC, dasimagin approved these changes

2024-07-09 16:26 UTC, dasimagin commented on packages/geom/test/boost_tests.cpp
> +}
Я предлагаю сделать группировку все же по типам. И на каждую регистрацию делать по тесту, а внутри теста уж сразу все инварианты проверять. Мне кажется, так логичнее. set/get оч удобно объединить в одни тест. Выстави и тут же проверил )

2024-07-09 16:26 UTC, dasimagin commented on packages/geom/test/boost_tests.cpp
> +}
Это косвенный тест, давайте лучше явно проверять то, что мы регистрировали. Давайте проверим каждую строчку регистрации.

2024-07-09 16:26 UTC, dasimagin commented on packages/navigation/include/navigation/graph_builder.h
> +// #include "geom/boost/point.h"
М?

2024-07-09 16:44 UTC, funham commented on packages/geom/test/boost_tests.cpp
> +}
Тут понадобятся дополнительные разъяснения)

2024-07-09 16:50 UTC, funham commented on packages/geom/test/boost_tests.cpp
> +}
хотя, кажется, я понял

2024-07-10 10:38 UTC, apmilko commented on packages/geom/test/boost_tests.cpp
> +}
Идея вынести повторяющийся код хорошая, но его не так много + когда смотришь тесты, то не хочется подниматься вверх по коду, чтобы узнать, что делает функция `geometry_from_points`, поэтому от этой идеи я отказался.

Названия функций мы пишем в стиле `functionName` вместо `function_name`.

2024-07-10 10:38 UTC, apmilko commented on packages/geom/test/boost_tests.cpp
> +}
При чтении тестов приходилось вникать, что делает `equal_points`, немного путает эта функция, от неё отказался.

2024-07-10 10:38 UTC, apmilko commented on packages/geom/test/boost_tests.cpp
> +}
Представь, что при регистрации типов ты случайно перепутал местами `min` и `max` в `geom::Segment`. Твой тест это не поймает, понимаешь почему?

Аналогично и для типа `geom::Segment`, там потеницально ты мог перепутать `begin` и `end`.

2024-07-10 13:12 UTC, funham commented on packages/geom/test/boost_tests.cpp
> +}
Хорошо. Буду иметь в виду.

2024-07-10 13:12 UTC, funham commented on packages/geom/test/boost_tests.cpp
> +}
А стайл гайд более подробный существует для этого проекта?

2024-07-10 13:14 UTC, funham commented on packages/geom/test/boost_tests.cpp
> +}
Идея была в том, чтобы сократить количество копирования, действительно, этот тест слишком маленький и простой, чтобы для него делать доп. функции.

2024-07-10 13:15 UTC, funham commented on packages/geom/test/boost_tests.cpp
> +}
У меня больше вопросов нет, но чтобы мне начать работать над следующей задачей, надо замержить эту ветку.

2024-07-10 13:25 UTC, apmilko commented on packages/geom/test/boost_tests.cpp
> +}
> А стайл гайд более подробный существует для этого проекта?

[Существует](https://github.com/robotics-laboratory/cookbook/blob/master/cpp/style.md#naming).

Когда ты пишешь очередной пакет `package_name`, то перед тем, как открыть с ним PR, всегда нужно выполнять два шага:
- выполнить команду `pre-commit run --all-files`, которая форматирует файлы проекта по указанным [здесь](https://github.com/robotics-laboratory/truck/blob/master/.pre-commit-config.yaml) инструкциям (для ознакомления), среди этих инструкций есть плюсовый [форматер](https://github.com/robotics-laboratory/truck/blob/master/.clang-format) `.clang-format`

- выполнить команду `make lint packages="package_name"`, которая прогонит плюсовый [линтер](https://github.com/robotics-laboratory/truck/blob/master/.clang-tidy) `.clang-tidy` на твоем пакете `package_name`, линтер много что проверяет, в том числе и корректность стиля твоего кода

2024-07-10 13:27 UTC, apmilko approved these changes

2024-07-10 14:20 UTC, merged