grid, gridholder and visualization_node format fix
robotics-laboratory/truck pull request #69
Opened 2023-07-13 18:35 UTC by thenromanov

Реализовал grid и holder для библиотеки fastgrid.
Чуть-чуть поправил косяки по кодстайлу в visualization_node.

2023-07-14 20:11 UTC, dasimagin commented on packages/fastgrid/package.xml
> +  <description>Library with algorithms for fast computitions on grid</description>
Мы прям свои пакеты не делаем, тут не принципиально, что писать )

2023-07-14 20:12 UTC, dasimagin commented on packages/fastgrid/include/fastgrid/grid.h
> +        : size(size), resolution(resolution), origin(origin) {}
Это `clang` так делает?

2023-07-14 20:14 UTC, dasimagin commented on packages/fastgrid/include/fastgrid/holder.h
> +    return ptr;
`std::make_unique<T[]>()`?

2023-07-14 20:15 UTC, dasimagin commented on packages/fastgrid/include/fastgrid/holder.h
> +    }
Я бы `move`-нул, но так тоже можно )

2023-07-14 20:16 UTC, dasimagin commented on packages/fastgrid/include/fastgrid/holder.h
> +    }
Лучше бы вызвать конструктор выше :)

2023-07-14 20:19 UTC, dasimagin commented on packages/fastgrid/test/main.cpp
> +    const int64_t big_value = 1e9 + 7;
Странная операция, там же внутри `int`...

2023-07-14 20:20 UTC, dasimagin commented on packages/fastgrid/include/fastgrid/grid.h
> +    size_t height = 0;
Строго рекомендую использовать тут `int`, это поможет не делать миллион кастов в коде потом :)

2023-07-14 20:24 UTC, dasimagin requested changes

2023-07-14 20:24 UTC, dasimagin commented on packages/fastgrid/test/main.cpp
> +TEST(Size, workability) {
Забавное название )

2023-07-14 20:24 UTC, dasimagin commented on packages/fastgrid/test/main.cpp
> +    const int64_t big_value = 1e9 + 7;
Понял, у вас `size_t`, написал коммент.

2023-07-14 20:24 UTC, dasimagin commented on packages/fastgrid/test/main.cpp
> +    const int64_t big_value = 1e9 + 7;
Не знаю, есть ли смысл тратить силы на такие тесты... лучше поберегите силы на нужные ;) может быть инстациацию я бы еще проверил... а так ¯\_(ツ)_/¯ (мое личное мнение).

2023-07-14 20:36 UTC, thenromanov commented on packages/fastgrid/include/fastgrid/grid.h
> +        : size(size), resolution(resolution), origin(origin) {}
У меня форматер из .clang-fromat из корня директории настройки подгружает

2023-07-14 20:36 UTC, thenromanov commented on packages/fastgrid/include/fastgrid/holder.h
> +    return ptr;
Вообще тут RVO и в итоге это должно быть ок, но в целом согласен

2023-07-14 20:39 UTC, thenromanov commented on packages/fastgrid/include/fastgrid/holder.h
> +    }
Я так делаю из расчета, что ptr чем-то владеет. Если в него просто мувнуть, то по идее память утечет. А так с вызовом деструктора у rvalue ptr'а память точно почистится.

2023-07-14 20:40 UTC, thenromanov commented on packages/fastgrid/include/fastgrid/grid.h
> +    size_t height = 0;
После этих слов где-то заплакал один лектор по C++ из Яндекса

2023-07-14 20:48 UTC, thenromanov commented on packages/fastgrid/include/fastgrid/holder.h
> +    }
Посмотрел на cppreference про оператор копирования - все было бы ок, я кринжанул

2023-07-14 23:33 UTC, thenromanov commented on packages/fastgrid/include/fastgrid/grid.h
> +        : size(size), resolution(resolution), origin(origin) {}
Причина всех бед AlignAfterOpenBracket: AlwaysBreak в .clang-format

2023-07-15 22:18 UTC, thenromanov commented
Поправил комментарии
Дописал ManhattanDistance  и тесты к нему
Изменил параметр AlignAfterOpenBracket в .cmake-format, чтобы больше форматтер не кринжевал с отступами

2023-07-16 17:18 UTC, thenromanov commented
Перегрузил оператор [] для гриба, чтобы обращаться как к 2D вектору и поправил все обращения в коде.

2023-07-16 23:24 UTC, thenromanov commented
Добавил модуль DistanceTransformApprox и соответствующие тесты.
Для вычисления DistanceTransformApprox использую алгоритм Chamfer distance transform

2023-07-17 01:04 UTC, thenromanov commented
Добавил модуль BilinearInterpolation, тесты к нему.
Переделал формат тестов для ManhattanDistance

2023-07-18 20:56 UTC, dasimagin commented on packages/fastgrid/include/fastgrid/grid.h
> +        : size(size), resolution(resolution), origin(origin) {}
Значение [параметра](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#alignafteropenbracket) для связанности... давайте вернем лучше, как было. Как на примере ниже, как по мне, отстойно будет выглядеть с длинными именами функций.

```
someLongFunction(argument1,
                 argument2);
```

Лучше какой-то из вариантов снизу:
```

someLongFunction(argument1,
    argument2);

someLongFunction(
    argument1, argument2);
```

2023-07-18 20:57 UTC, dasimagin commented on packages/fastgrid/include/fastgrid/holder.h
> +    return ptr;
Так дело не в RVO, просто за нас это "написали" уже :)

2023-07-18 20:57 UTC, dasimagin commented on packages/fastgrid/include/fastgrid/holder.h
> +    }
Кринжанули, ничего не утечет )

2023-07-18 20:59 UTC, dasimagin commented on packages/fastgrid/include/fastgrid/grid.h
> +    size_t height = 0;
Я сам фанат `size_t`, я его везде пишу. Но потом у нас будет много хитрых операций над указателями (будем активно складывать и вычитать, вы там заплачете возиться с `size_t`).

2023-07-18 21:04 UTC, thenromanov commented on packages/fastgrid/include/fastgrid/holder.h
> +    return ptr;
Да-да я согласен, все поправил

2023-07-18 21:04 UTC, merged