Primitives Generation (Latest) [A* Planner]
robotics-laboratory/truck pull request #80
Opened 2023-08-18 12:20 UTC by andrew-milko

2023-08-20 18:11 UTC, dasimagin requested changes

2023-08-20 18:11 UTC, dasimagin commented on packages/planner/primitives.py
> +    style = 2: points with theta angles
В питоне тут часто строки для таких дел используют, тогда все это писать и не надо будет, эдакая самодокументация.

2023-08-20 18:11 UTC, dasimagin commented on packages/planner/primitives.py
> +  plt.ylim([-1.2, 1.2])
мб лучше потребовать просто равномерный scale и не хардкодить размер?

2023-08-20 18:11 UTC, dasimagin commented on packages/planner/primitives.py
> +  "primitives_indices": {
Здесь предполагается деление по `yaw_index`? МБ тогда и назвать попонятнее?

**P.S.** Здорово, что схему джейсона обозначили.

2023-08-20 18:11 UTC, dasimagin commented on packages/planner/primitives.py
> +      "start_yaw_index": 10
1. Конечный `yaw` не так интересен?
2. Думаете, хранить список троек менее удобно `[(x, y, theta),...]`, тут просто читая поток json можно сразу подпозы делать в ребре. ?

2023-09-01 10:19 UTC, andrew-milko commented on packages/planner/primitives.py
> +      theta [double]: angle rad in interval [-min_theta; max_theta)
Да, я гарантированно подаю в эту функцию угол из этого полуинтервала

2023-09-01 10:27 UTC, andrew-milko commented on packages/planner/primitives.py
> +    theta[i] = math.remainder(theta[i], 2 * math.pi)
Гарантия в 79-ой строчке: я воспользовался функцией для конвертации угла внутрь отрезка `[-pi; pi]`: https://stackoverflow.com/a/61485110

2023-09-01 10:32 UTC, andrew-milko commented on packages/planner/primitives.py
> +      theta[i] = -math.pi
В 79-ой строчке я конвертировал угол `theta[i]` внутрь отрезка `[-pi; pi]`. А поскольку во всех функциях тетрадки я хочу работать с углами в полуинтервале `[-pi; pi)`, то при получении угла `pi` мне нужна отобразить его в угол `-pi`, чтобы удовлетворить условию на нахождения угла в полуинтервале `[-pi; pi)`.

2023-09-01 10:53 UTC, andrew-milko commented on packages/planner/primitives.py
> +  "primitives_indices": {
> Здесь предполагается деление по `yaw_index`?

Да

> МБ тогда и назвать попонятнее?

Поменял `primitives_indices` > `yaw_to_primitives_indices`

2023-09-01 11:54 UTC, andrew-milko commented on packages/planner/primitives.py
> +      primitives += [buildPrimitive(config, start_pose, end_pose)]
> Да, так можно, но еще есть `append`. Тут в целом это не важно, но питон дико медленный, а тут еще промежуточный список создается.

Заменил на `append`.

2023-09-01 12:03 UTC, andrew-milko commented on packages/planner/primitives.py
> +    style = 2: points with theta angles
> В питоне тут часто строки для таких дел используют, тогда все это писать и не надо будет, эдакая самодокументация.

Исправил.

2023-09-01 12:36 UTC, andrew-milko commented on packages/planner/primitives.py
> +  plt.ylim([-1.2, 1.2])
> мб лучше потребовать просто равномерный scale и не хардкодить размер?

Исправил.

2023-09-01 12:40 UTC, andrew-milko commented on packages/planner/primitives.py
> +  m.obj = Objective(expr=m.tf + m.integral)
> Это я такую функцию потерь предлагал или вы из каких-то соображения ее выбрали?

Вы :)

2023-09-01 13:20 UTC, andrew-milko commented on packages/planner/primitives.py
> +  index = round((theta + math.pi) / yaw_step)
> Нулевой yaw смотрит в направлении `-y` или я что-то не так понял?

Нет.

Насколько я понял, вас смутило прибавление к углу `theta` значениея `math.pi`, в 55-ой строчке.

Я гарантирую, что на вход этой функции подается угол из полуинтервала `[-pi; pi)`.

Прибавлением к нему значения `math.pi` я перевожу его в полуинтервал `[0; pi)`, чтобы потом делением на `yaw_step` и дальнейшим округлением получить ближайший индекс.

2023-09-01 13:36 UTC, andrew-milko commented on packages/planner/primitives.py
> +  primitive['start_yaw_index'] = getYawIndexFromTheta(primitive['theta'][0], yaw_step)
> В финальном `yaw` нет необходимости?

На самом деле такая необходимость есть.

Просто в тетрадке мы нигде этим пользоваться не будем, а вот в плюсовом коде я уже в пару местах пользуюсь индексом финального `yaw`, поэтому все-таки посчитаю и сохраню его в поле `primitive[end_yaw_index]`, чтобы в плюсовом коде не делать этого, а просто выдернуть уже посчитанное значение из `json`.

2023-09-01 13:44 UTC, andrew-milko commented on packages/planner/primitives.py
> +      "start_yaw_index": 10
> 1. Конечный `yaw` не так интересен?

Интересен, теперь решил его сохранять, подробнее [здесь](https://github.com/robotics-laboratory/truck/pull/80#discussion_r1313040399).

> 2. Думаете, хранить список троек менее удобно `[(x, y, theta),...]`, тут просто читая поток json можно сразу подпозы делать в ребре. ?

Мне удобно иметь три отдельных списка `x, y, theta`. Поскольку мы считывание `json` делаем ровно один раз при инициализации пайплайна, то думаю особо нету разницы, как именно хранить примитивы, т.к. на перфе это отрицательно не скажется

2023-09-06 09:14 UTC, andrew-milko commented on packages/planner/primitives.py
> +        where beta = atan(0.5 * L * tan(phi))
> Я не поленился проверить формулки (хотя это не должно быть моей работой), у меня получилось иначе... давайте думать, у кого ошибки...

Я несколько раз перепроверил мою формулу вычисления `beta` (у вас это `alpha`), ошибка оказалась у меня: в моей формуле была лишняя переменная `L`.

Было (неправильно): `beta = atan(0.5 * L * tan(phi))`

Надо (правильно): `beta = atan(0.5 * tan(phi))`

2023-09-06 09:21 UTC, andrew-milko commented on packages/planner/primitives.py
> +      return m.theta_dot[t] == (config['v_max'] / config['L'] * tan(m.phi[t]) * cos(beta)) * m.tf
> 1. Название `ode_a` путает, лучше `ode_theta`.

Сделал.

> 2. Какой физический смысл у `phi` и `theta`, а то я не понимаю тут роль `beta`...

- `phi` - угол поворота колес
- `theta` - направление машинки относительно оси `x`
- `beta` - это угол `alpha` на вашем [рисунке](https://github.com/robotics-laboratory/truck/pull/80#discussion_r1299413037)

2023-09-06 09:28 UTC, andrew-milko commented on packages/planner/primitives.py
> +      config (L, an_max, v_max, w_max, phi_max, density) [dict]: optimization parameters
> Это достаточно смутная дока получается, без контекста фиг угадаешь, какая буква что значит.

Идея объяснять значений полей конфига в каждой функции, где он используется, мне не очень нравится.

Когда я определяю конфиг, я даю расшифровку всех его полей ([здесь](https://github.com/robotics-laboratory/truck/pull/80/files#diff-99b6ad3f14ab00d3c6c4a9fed4f1cf32b795e99f4e73a98b5bad645380c4b0afR280)). Думаю, этого достаточно.

2023-09-23 17:15 UTC, dasimagin commented on packages/planner/primitives.py
> +helper.install_ipopt()
Хм, кажется, у нас только `ipopt` явно не прописан, сделаем :)

2023-09-23 17:27 UTC, dasimagin commented on packages/planner/primitives.py
> +      "start_yaw_index": 10
Да, но такая структура может спровоцировать вас на ошибку, надо делать проверки, что списки одинаковой длины и т.п. почему это не один список решительно сложно понять ¯\_(ツ)_/¯ почему так удобнее?

2023-09-23 17:32 UTC, dasimagin commented on packages/planner/primitives.py
> +helper.install_ipopt()
Почему код так и не убран? М?

2023-10-07 11:21 UTC, andrew-milko commented on packages/planner/primitives.py
> +  index = round((theta + math.pi) / yaw_step)
> Мой вопрос остается открытым, куда смотрим `yaw` с индексом 0?

`yaw` с нулевым индексом смотрит в направлении `-x`. Так, например, если у нас есть угол `theta = -PI`, то ему как раз будет соответствовать `yaw` с нулевым индексом.

2023-10-07 11:21 UTC, andrew-milko commented on packages/planner/primitives.py
> +  index = round((theta + math.pi) / yaw_step)
> Ну и добавление `PI`, очевидно, переведет вас в полуинтервал `[0; 2PI)`, а не `[0; PI)`

Да, я опечатался.

2023-10-07 12:05 UTC, andrew-milko commented on packages/planner/primitives.py
> +  index = round((theta + math.pi) / yaw_step)
> А еще я не понимаю, как работает эта функция.

Просьба смотреть на версию этой функции после последнего коммита, надо было исправить багу.

___

Объяснение:

1. Мы получаем на вход угол `theta` в  полуинтервале `[-PI; PI)`, для этого угла хотим узнать индекс ближайшего к нему угла `yaw`

2. Количество `yaw` углов определяется переменной `yaws_count`, поэтому ожидаем что наша функция выдаст целое число из отрезка `[0, (yaws_count - 1)]`

3. Шаг между парой соседних `yaw` обозначим как `yaw_step = math.radians(360 / yaws_count)`

4. Прибавлением к углу `theta` значения `PI` я перевожу его в полуинтервал `[0; 2PI)`, обозначим такой угол как `theta* = theta + PI`

5. Далее я смотрю, сколько ЦЕЛЫХ раз в угол `theta*` поместилось значение `yaw_step`, делая приэтом арифмитическое округление, и сохраняю это число в переменной `index = round((theta*) / yaw_step)`
 
6. В переменной `index` гарантированно (из-за ограничений на значение угла `theta`) будет хранится какое-то целое число из отрезка `[0, yaws_count]`, что противоречит желаемому выходу функции, описанному в пункте 2

7. Противоречие возникает из-за того, что `index` может равняться `yaws_count` (в этом и была бага), пример такой ситуации на фото: в таких ситуациях надо просто менять значение переменной `index` с `yaws_count` на `0`, т. к. именно `yaw` с нулевым индексом и является ближайшим к заданному углу `theta`

![image](https://github.com/robotics-laboratory/truck/assets/80720287/bf7a8a34-bc20-42a9-8b00-01e51a759ec2)

2023-10-07 12:54 UTC, andrew-milko commented on packages/planner/primitives.py
> +    self.density = density
Классы `Pose`, `Primitive` и `Config` переписал сделал через `dataclass`. Код стал приятнее.

P.S.: к классу `PrimitiveEncoder` не добавлял `dataclass`, т.к. не вижу в этом смысла.

2023-10-07 13:25 UTC, andrew-milko commented on packages/planner/primitives.py
> +    self.end_yaw_index = int
> Это вы в переменную класс кладете... а зачем? :)

Кринжанул, теперь в коде такого нет.

2023-10-07 13:27 UTC, andrew-milko commented on packages/planner/primitives.py
> +    if theta == math.pi: theta = -math.pi
Вы про это уже спрашивали: https://github.com/robotics-laboratory/truck/pull/80#discussion_r1312863667

2023-10-07 14:00 UTC, andrew-milko commented on packages/planner/primitives.py
> +      to the middle of the robot's wheelbase (L/2) using these formulas:
> У нас `base` не всегда середина робота, там есть конкретная константа.

Исправил. Прилагаю [видео](https://www.youtube.com/watch?v=HqNdBiej23I), где есть вывод всех формул.

2023-10-07 14:13 UTC, andrew-milko commented on packages/planner/primitives.py
> +      return m.theta_dot[t] == (config.v_max / config.L * tan(m.phi[t]) * cos(beta)) * m.tf
> Как получена эта строчка?

Вывод формулы `theta_dot` есть в этом [видео](https://www.youtube.com/watch?v=HqNdBiej23I).

В этой формуле не важно, какое расстояние от `base` до задней оси, важна только общая длина робота. Я не прав?

Ваши выкладки я не очень понял, особенно что такое переменная `C`.

2023-10-07 14:52 UTC, andrew-milko commented on packages/planner/primitives.py
> +  primitive.end_yaw_index = getYawIndexFromTheta(primitive.theta_arr[-1], yaw_step)
> Не сильно понятно, зачем это отдельно хранить...

- Индексом `start_yaw_index` я пользуюсь [здесь](https://github.com/robotics-laboratory/truck/blob/9ef8a0e0bd08b68b8113e5e2fd8e02347962aabb/packages/planner/primitives.py#L832) для группировки примитивов по общему индексу начального `yaw`

- Индексом `end_yaw_index` я пользуюсь в своей функции поиска траектории: пусть я от существующей вершины хочу пойти в соседнюю вершину (не известно, существует ли она или нет) по примитиву. Чтобы узнать, существует ли в конечной точке этого примитива вершина, как минимум, надо знать индекс `yaw` в последней точке примитива. Мне не нравится идея считать этот индекс в коде, лучше уж просто выдернуть его из `json`. Я хочу всю логику с преобразованием углов в индексы максимально спрятать в `.ipynb` тетрадку

Если не убедил, то давайте, пожалуйста, все равно оставим этот кусок кода и более содержательные вещи лучше исправим :)

2023-10-07 15:22 UTC, andrew-milko commented on packages/planner/primitives.py
> +    self.theta_arr = list()
> А почему все же 3 списка удобнее, чем один?

Так очень удобно [рисовать](https://github.com/robotics-laboratory/truck/blob/9ef8a0e0bd08b68b8113e5e2fd8e02347962aabb/packages/planner/primitives.py#L268) примитивы, например.

2023-10-07 15:37 UTC, andrew-milko commented on packages/planner/primitives.py
> +helper.install_ipopt()
> Почему код так и не убран? М?

Теперь убран. Проверю, действительно ли нужные пакеты есть, запущу эту ячейку в контейнере.

2023-10-07 15:39 UTC, andrew-milko commented on packages/planner/primitives.py
> +      "start_yaw_index": 10
Если [это ](https://github.com/robotics-laboratory/truck/pull/80#discussion_r1349534409) не аргумент, то если наставиваете, сделаю одним списком.

2023-10-14 19:58 UTC, dasimagin approved these changes

2023-10-14 19:58 UTC, dasimagin commented on packages/planner/primitives.py
> +import requests
Не вижу использования 2 этих модулей.

2023-10-14 19:58 UTC, dasimagin commented on packages/planner/primitives.py
> +    return json.JSONEncoder.default(self, obj)
Разве я не писал, то так лучше не делать? Напишите уж лучше тогда явный метод.

2023-10-14 19:58 UTC, dasimagin commented on packages/planner/primitives.py
> +  phi_max: float        # max steering angle rad
Вы же понимаете, что для этого числа нельзя наивно брать [outter/inner](https://github.com/robotics-laboratory/truck/blob/f3662aeac35534013d567b5d1231169593e30841/packages/model/config/model.yaml#L13)?

2023-10-14 19:58 UTC, dasimagin commented on packages/planner/primitives.py
> +  index = round((theta + math.pi) / yaw_step)
Это уже больше похоже на правду )

Немного странно, что точка отсчета выбрана в направлении `x=-1,y=0`, но доводов почему так "нельзя" делать, у меня нет. Я бы конечно сделал начало с `x=1,y=0`.

2023-10-14 19:58 UTC, dasimagin commented on packages/planner/primitives.py
> +  return index
Уж лучше тогда `return index if index != yaws_count else 0`

2023-10-14 19:58 UTC, dasimagin commented on packages/planner/primitives.py
> +    if theta == math.pi: theta = -math.pi
```
if theta == math.pi:
  theta = -math.pi
```

2023-10-14 19:58 UTC, dasimagin commented on packages/planner/primitives.py
> +    phi_max = 0.7,
Это чутоку выше 40, внутренний угол воображаемго центрального колеса всегда будет чуточку меньеш, если `inner/outer=40` в нашем конфиге, но пока можно забить.

2023-10-16 12:16 UTC, andrew-milko commented on packages/planner/primitives.py
> +    phi_max = 0.7,
> Это чутоку выше 40, внутренний угол воображаемго центрального колеса всегда будет чуточку меньеш, если `inner/outer=40` в нашем конфиге, но пока можно забить.

Да, 0.7 радиан ~ 40.1 градусов, вылезди из ограничения в 40 градусов) Поменял значение `phi_max` на `0.695`, чтобы вписываться в ограничение на 40 градусов и не строить примитивы "впритык" максимальным возможностям машинки

2023-10-16 12:55 UTC, merged