Initial 2d simulator
robotics-laboratory/truck pull request #81
Opened 2023-08-24 00:23 UTC by Oleg-Olegovich

Added:
- Simulator engine.
- Simulation state (struct for engine).
- Simulator node.

Changed:
- Model configuration
- Visualization node (wheels added)
- Control_proxy (restoring acceleration with manual operation)

Known issues:
- Incorrect calculations of the simulation engine. The rotation point is offset. There may be an error in the integration.

2023-09-17 19:24 UTC, dasimagin requested changes

2023-09-17 19:24 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +        }
В классе `Angle` уже есть нормализация.

2023-09-17 19:24 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +                        abs(steering_velocity) * params_.integration_step / 6;
1. Так не стоит делать, заведите другую переменную... это оч тяжело читать.
2. Можно пояснение, откуда деление на 6?
3. Ничего не понял... вроде, там надо просто сравнить "перелетим ли мы через границу", но я не понимаю, что вы тут делаете.

2023-09-17 19:24 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +        }
Те же вопрос...

2023-09-17 19:24 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +        state_ += (k1 + 2 * k2 + 2 * k3 + k4) * (params_.integration_step / 6);
Лучше закэшить все деление на 2 и 6, а то воздух зря греем.

2023-09-17 19:24 UTC, dasimagin commented on packages/simulator_2d/src/simulator_node.cpp
> +    engine_.start(model, this->declare_parameter("integration_step", 0.001), params_.precision);
Можно мувнуть.

2023-09-17 19:24 UTC, dasimagin commented on packages/simulator_2d/src/simulator_node.cpp
> +    odom_msg.twist.twist.angular.y = angularVelocity.y;
Мы же можем только вокруг `z` вращать? Ну-ка идите и разберитесь, что это за штука :)

2023-09-17 19:24 UTC, dasimagin commented on packages/simulator_2d/src/simulator_node.cpp
> +    odom_msg.pose.pose.orientation.w = quaternion.w;
1. А зачем потом рукам то копировать? Вы и так сообщение уже сделали...
2. У нас уже оч Богатая библиотека геометрическая и там многие объекты отлично превращаются в эти сообщения, идите покопайтесь, допишите, если чего не хватает.

2023-09-17 19:24 UTC, dasimagin commented on packages/simulator_2d/src/simulator_node.cpp
> +    odom_to_base_transform_msg.transform.rotation.w = quaternion.w;
Тут две строки надо всего написать )

2023-09-17 19:24 UTC, dasimagin commented on packages/simulator_2d/src/simulator_node.cpp
> +    telemetry_msg.header.frame_id = "odom_ekf";
Там скорее `base`...

2023-09-17 19:24 UTC, dasimagin commented on packages/simulator_2d/src/simulator_node.cpp
> +void SimulatorNode::publishSimulationStateMessafe(const rclcpp::Time &time,
Очепятка?

2023-09-17 19:24 UTC, dasimagin commented on packages/simulator_2d/src/simulator_node.cpp
> +    const auto time = now();
1) ну надо де указывать время симулятор, а не системы...
2) еще надо в `/clock` публиковать, запустите старый симулятор, посмотрите, что там за тип сообщения и как там пишется именно симуляторное время.

2023-09-26 02:17 UTC, Oleg-Olegovich commented on docker-compose.yaml
> +      - ".:/truck"
Не обсуждали, не посчитал важным.
Мне замена на точку помогла как в Ubuntu, так и в WSL. Но я не разбираюсь в этом, поэтому утверждать ничего не буду. На настоящий момент выполнен rebase, содержимое этого файла идентично текущей версии в master.

2023-09-26 02:19 UTC, Oleg-Olegovich commented on packages/model/config/model.yaml
> +  y_offset: 0.11168 # m (absolute value)
Как можно вычислить такой y_offset из текущей wheel_base? Я взял значение из "чертежа".
Возможно, есть какая-то формула, которая позволяет однозначно установить расположение колёс по длине и ширине колёсной базы, но я такую не знаю. Оставил параметры для гибкости конфигурации.

2023-09-26 02:22 UTC, Oleg-Olegovich commented on packages/visualization/src/visualization_node.cpp
> +        msg.scale.x = msg.scale.y = 2 * model_->wheel().radius;
Извините, про что конкретно речь? Как надо?

2023-09-26 02:28 UTC, Oleg-Olegovich commented on packages/simulator_2d/include/simulator_2d/simulator_engine.h
> +    };
Так мне и нужно вычислять угловую скорость, для одометрии. Если я это делаю неправильно, тогда надо менять код вычисления, а не название.

2023-09-26 02:31 UTC, Oleg-Olegovich commented on packages/simulator_2d/include/simulator_2d/simulator_engine.h
> +        double steering_limit;
Да, есть. Мне не понравилось каждый раз по ссылке обращаться к model и доставать оттуда значения. Разыменовывание - дорогая операция, плюс так код мне кажется компактнее. Но если вы считаете, что это всё ерунда - выпилю.

2023-09-26 02:33 UTC, Oleg-Olegovich commented on packages/simulator_2d/include/simulator_2d/simulator_engine.h
> +        const double precision = 1e-8);
Чтобы в SimulatorNode хранить экземпляр SimulatorEngine по значению и обращаться к нему без разыменовывания. Если в конструкторе есть аргументе, то с этим возникают сложности. Но это, вероятно, ерунда для вас, исправлю.

2023-09-26 02:40 UTC, Oleg-Olegovich commented on packages/visualization/src/visualization_node.h
> +        const geometry_msgs::msg::Pose &pose) const;
Тогда нужно через аргументы туда передавать state_, model_, params_. Норм?

2023-09-30 17:51 UTC, dasimagin commented on packages/model/config/model.yaml
> +  y_offset: 0.11168 # m (absolute value)
Ну у вас же есть `wheel_base`, там все написано...

Для задних колес:
```
x_offset: -base_to_rear
y_offset: width/2
```

Для передних колес:
```
x_offset: lenght-base_to_rear
y_offset: width/2
```

2023-09-30 17:51 UTC, dasimagin commented on packages/simulator_2d/include/simulator_2d/simulator_engine.h
> +        const double precision = 1e-8);
Поясните, что за сложности... можно со снипетами кода.

2023-09-30 17:51 UTC, dasimagin commented on packages/simulator_2d/include/simulator_2d/simulator_engine.h
> +        double steering_limit;
Есть статьи или тесты с доказательством? Возможно, вы недооцениваете современные компиляторы и процессоры.

Я еще готов поверить, что в каких-то диких циклах вы это может почувствовать, но тут... но там не сложно по месту все в константы разложить перед циклом. Плодить сущности опасно может быть, потом за ними следить нужно...


Ну и всегда для удобства можно делать.

```
const auto& param = model.get.smth.with.lont.path;
f(param);
```

А если там что-то легкое, то значение даже захватить.

2023-09-30 17:51 UTC, dasimagin commented on packages/simulator_2d/include/simulator_2d/simulator_engine.h
> +    };
Ок

2023-09-30 17:51 UTC, dasimagin commented on packages/truck_msgs/msg/SimulationState.msg
> +float64 steering
В повороте да, это не сложно показать формулками, вы даже сами можете вывести для base и центра задней оси :)

**P.S.** `speed`, это значит, что скаляр неотрицательиный всегда?

2023-09-30 17:51 UTC, dasimagin commented on packages/visualization/src/visualization_node.cpp
> +        msg.scale.x = msg.scale.y = 2 * model_->wheel().radius;
два равно в одной строке )

2023-09-30 17:51 UTC, dasimagin commented on packages/visualization/src/visualization_node.h
> +        const geometry_msgs::msg::Pose &pose) const;
А зачем это передавать? Я помню, что писал рекомендации, как все получше организовать )

2023-10-12 23:31 UTC, Oleg-Olegovich commented on packages/truck_msgs/msg/SimulationState.msg
> +float64 steering
velocity - вектор, а speed - скалярная величина. Наверное, вы правы.

2023-10-13 00:30 UTC, Oleg-Olegovich commented on packages/simulator_2d/src/simulator_engine.cpp
> +                                            +params_.steering_limit);
Надо будет на созвоне обсудить кэширование.

2023-10-13 01:36 UTC, Oleg-Olegovich commented on packages/simulator_2d/src/simulator_engine.cpp
> +}
Передавать вектор или по аргументу на каждый аргумент вектора? Если последнее, то это вроде ухудшит изменяемость кода.
Нужно ли уметь задавать произвольную скорость в начале?

2023-10-13 03:03 UTC, Oleg-Olegovich commented on packages/simulator_2d/src/simulator_engine.cpp
> +void SimulatorEngine::start(
По const& не получилось, потому что у модели нет конструктора по умолчанию (без аргументов).

2023-10-16 04:48 UTC, Oleg-Olegovich commented on packages/simulator_2d/src/simulator_engine.cpp
> +    const auto curvature_limit = model_->baseMaxAbsCurvature();
1. Не понял, что имеется в виду под предпосчитанным классом.
2-3. Добавил методы в model. Надо проверить, не ошибся ли я.
Не придумал, как переводить ускорение центра в ускорение задней оси.

2023-10-16 04:48 UTC, Oleg-Olegovich commented on packages/simulator_2d/src/simulator_engine.cpp
> +    params_.steering_limit = model_->leftSteeringLimits().max.radians();
На созвоне нужно будет обсудить: добавить параметр для "внутреннего" колеса в конфиг или как-то считать это значение в Runtime.

2023-10-30 16:52 UTC, closed without merging