Simulator base (PR mini)
robotics-laboratory/truck pull request #87
Opened 2023-10-26 05:29 UTC by Oleg-Olegovich

Здесь все мелкие исправления в других пакетах, полноценная нода симулятора и обрезанный движок: выпилил из расчётов steering и yaw, но API менять не стал.

График локализации в foxglove всё ещё немного дёрганный, смущает меня. В самом начале через раз-два случается проскок вперёд на 4 см.

Безумие происходит с трансформацией из odom_ekf в base (метод SimulatorNode::publishTranslationMessage). Правильный результат получается только при использовании "наивной" летней реализации. "Умный" вариант с инвертированием трансформации заставляет base улетать куда-то в километр от центра машинки (не шучу, иногда очень далеко, правда, тут undefined behavior).

2023-10-30 16:42 UTC, dasimagin requested changes

2023-10-30 16:42 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +        .finished();
Красивое )

2023-10-30 16:42 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +}
`const rclcpp::Time&`?

2023-10-30 16:42 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +    pose.pos.x = state_[StateIndex::x] + model_.wheelBase().base_to_rear;
1. Если едем только по прямой то да, так проканает. Не забудьте потом поправить.
2. getBasePose?

2023-10-30 16:42 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +}
Для какой части машинки это? Rear? Base? отразите в названии!

2023-10-30 16:42 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +}
Я бы сделал только один метод, когда возращает всю структурку. Ниже вы его и написали...

2023-10-30 16:42 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +}
В целях "ортоганализации" методов предлагаю сделать только твисты, остальное не сильно понятно зачем нужно :)

2023-10-30 16:42 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +}
Летает и крякает, как метод структурки твиста ;)

2023-10-30 16:42 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +    }
Почему так? А если назад поедем?
`acc_max` – ускорение набор скорости
`acc_min` – ускорение торможения

2023-10-30 16:42 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +    const SimulatorEngine::State &state, double acceleration) {
Вроде, это производная называется ))))

2023-10-30 16:42 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +        }
1. А если нас просят тормозить до чего положительноного?
2. А где проверка, что мы не проскочим при этот инкременте?

2023-10-30 18:02 UTC, Oleg-Olegovich commented on packages/geom/include/geom/angle.h
> +        return (result < 0) ? result + 2 * M_PI : result;
Я просто боюсь переполнения. Например, при длительном вращении. Возможно, напрасно.

2023-10-31 01:35 UTC, Oleg-Olegovich commented on packages/simulator_2d/CMakeLists.txt
> +find_package(visualization REQUIRED)
rosgraph_msgs нужен для
#include <rosgraph_msgs/msg/clock.hpp>

2023-10-31 01:44 UTC, Oleg-Olegovich commented on packages/simulator_2d/src/simulator_node.cpp
> +    odom_msg.child_frame_id = "odom_ekf";
Вроде бы всё верно.

2023-10-31 02:38 UTC, Oleg-Olegovich commented on packages/simulator_2d/include/simulator_2d/simulator_engine.h
> +    geom::Vec2 getAngularVelocity() const;
Структура Twist содержит 2 double: velocity и curvature.
getLinearVelocity возвращает структуру Vec2. Если удалить этот метод, пользователям движка для получения этого вектора придётся писать это:
geom::Vec2::fromAngle(geom::Angle(getTwist().velocity));
Наличие метода в API позволяет избежать дублирования кода.

2023-10-31 03:36 UTC, Oleg-Olegovich commented on packages/simulator_2d/src/simulator_node.cpp
> +        .update_period = declare_parameter("update_period", 0.01)};
Не понял. У меня же уже есть структура с параметрами в ноде (Parameters).

2023-10-31 03:44 UTC, Oleg-Olegovich commented on packages/simulator_2d/src/simulator_engine.cpp
> +        }
Думаю, что нужно в control или state хранить, разгоняемся мы сейчас или тормозим.
При прохождении через ноль брать значение ускорения из model. При управлении с контроллера это никак не влияет, при управлении с автопилота (если нужно другое ускорение) исправляется одной командой setControl.

Что думаете?

2023-10-31 03:47 UTC, Oleg-Olegovich commented on packages/simulator_2d/src/simulator_engine.cpp
> +    }
Написал сейчас вот так:
```suggestion
    const auto limits = model_.baseAccelerationLimits();
    if (rear_ax_state_[StateIndex::linear_velocity] * velocity > 0) {
        const double current_speed 
            = abs(rear_ax_state_[StateIndex::linear_velocity] - params_.precision);
        if (current_speed < abs(velocity)) {
            acceleration = limits.max;
        } else {
            acceleration = limits.min;
        }

        if (velocity < 0) {
            acceleration *= -1;
        }
    }
    else {
        acceleration = limits.min;

        if (velocity > 0) {
            acceleration *= -1;
        }
    }

    setBaseControl(velocity, acceleration, curvature);
```

1. Если текущая скорость и требуемая одного знака, то мы просто разгоняемся или тормозим.
2. Иначе нам в любом случае нужно сначала остановиться, а потом уже разгоняться в другую сторону.
3. Для разгона в другую сторону в методе advance при прохождении через 0 проверяем, тормозили мы сейчас или нет. Если да, то переключаем флаг в "разгон" и берём значение ускорения из model.

Очень интересно ваше мнение.

2023-10-31 15:54 UTC, Oleg-Olegovich commented on packages/simulator_2d/src/simulator_engine.cpp
> +    }
Возможно, флаг не нужен и достаточно в моменте сравнивать текущую и требуемую скорости.

2023-10-31 17:10 UTC, Oleg-Olegovich commented on packages/simulator_2d/src/simulator_engine.cpp
> +        }
Сейчас написал так, уже интереснее:
`const double new_velocity 
            = rear_ax_state_[StateIndex::linear_velocity] + velocity_delta;
        const bool is_speed_up = isOutOfRange(control_.velocity, 
            rear_ax_state_[StateIndex::linear_velocity], params_.precision);
        const bool target_speed_achieved = is_speed_up
            ^ isOutOfRange(new_velocity, control_.velocity, params_.precision);
        if (target_speed_achieved) {
            rear_ax_state_[StateIndex::linear_velocity] = control_.velocity;
            acceleration = 0;
        }`

2023-11-11 22:13 UTC, dasimagin approved these changes

2023-11-11 22:13 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +        validateAcceleration(target_velocity);
Вот эта функция меня убила... путанная, непнонятная, что-то подменяет...
1) не меняйте изначальный контрол, сделайте копию, если что-то поклэмпать поменять надо...
2) я попробовал подумать, как бы я сам написал, вышло вот так...


```
struct State {
    double x;
    double v;
}


struct Control {
    double v;
    std::optional<double> a; // MAKE IT OPT! IT'S ABS VALUE :)
};


State calculateRK4(double v, double a) {
    // bla-bla-bla
}


int softSgn(double x, double eps) {
    if (x > eps) {
        return 1;
    } else if (x < -eps) {
        return -1;
    } else {
        0;
    }
}

double moreStrictAcc(const std::optional<double>& opt, double val) {
    if (!opt) {
        return val;
    }

    return min(*opt, val);
}

// Work with ctrl copy! I can change anything!
void Advance(...) {
    for (int i = 0; i < integration_steps; ++i) {
        auto v = v_lim.clamp(ctrl_.v);
        if (softSgn(v) * softSgn(state.v) < 0) {
            // make implicit stop
            v = 0;
        }

        const auto act_sign = softSign(abs(v) - abs(state.v));
        const auto a_sgn = softSign(v - state.v);
        
        double a = 0;

        if (act_sign == 1) {
            // acceleration
            a = a_sgn * moreStrictAcc(ctrl.a, acceleration_max);
        } else if (act_sign == -1) {
            // deceleration
            a = a_sgn * moreStrictAcc(ctrl.a, acceleration_max);
        }


        if (a_sgn > 0) {
            if (state.v + a*dt + eps > v) {
                a = (v - state.v) / dt;
            }
        } else if (a_sng < 0) {
            if (state.v + a*dt - eps < v) {
                a = (v - state.v) / dt;
            }
        }

        state_ += RK4(v, a);
    }
}
```

2023-11-11 22:13 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +            : control_.velocity;
Отличная идея )

2023-11-11 22:13 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +    double velocity, double acceleration, double curvature) {
Можно завести структурку контрола с опциальным ускорением, все станет лучше сразу )

2023-11-11 22:13 UTC, dasimagin commented on packages/simulator_2d/src/simulator_engine.cpp
> +}
В следующий раз побью за такую математику!

2023-11-11 22:13 UTC, dasimagin commented on packages/simulator_2d/include/simulator_2d/simulator_engine.h
> +    geom::Vec2 getBaseAngularVelocity() const;
Для удобства пользователя можно завести `TruckState` с удобными методами, но внутри хранить все, как сейчас...

2023-11-12 02:25 UTC, Oleg-Olegovich commented on packages/simulator_2d/src/simulator_engine.cpp
> +void SimulatorEngine::validateAcceleration(double& target_velocity) {
Так мы же по ссылке передаём: double&

2023-11-19 15:46 UTC, Oleg-Olegovich commented on packages/simulator_2d/src/simulator_node.cpp
> +    publishSimulationState();
Нет, лучше оставить, как есть. Пользователю нужно знать самое актуальное состояние. Будет нехорошо, если мы опубликуем старое состояние, в котором всё хорошо, потом машинка уезжает куда-то не туда, а сообщение об этом не опубликовано.

2023-11-20 20:24 UTC, merged