"Map" Library
robotics-laboratory/truck pull request #93
Opened 2023-12-08 15:37 UTC by andrew-milko

add 'map' library, add 'Polygon' & 'ComplexPolygon' structures, add map visualization

2023-12-10 00:54 UTC, dasimagin commented
Давайте еще раз уточню... мы все храним в стиле GeoJSON, но при этом хотим работать в метрах. Двигаться в сторону `lat,lon` не будем, чтобы удобно орудовать вьером? :)

2023-12-10 01:18 UTC, dasimagin requested changes

2023-12-10 01:18 UTC, dasimagin commented on packages/map/include/map/map_builder.h
> +class Map {
Давайте все же чуточку аккуратнее сделаем... Надо стараться не делать тяжелых операций в конструкторе, это больше про инициалзацию ресурсов. Я бы так предложил написать.

```
using ComplexPolygons = std::vector<ComplexPolygon>;

class Map {

public:
  Map(ComplexPolygons polygons);

  const ComplexPolygons& polygons() const;

  static Map fromGeoJson(const std::string& path);

private:
  ComplexPolygons polygons_;
};
```

2023-12-10 01:18 UTC, dasimagin commented on packages/map/include/map/map_builder.h
> +class Map {
То есть всю логику мы перекладыем в функцию, там собираем все полигоны и просто муваем в `Map`-у. При этом мы сразу делаем задел, что их может быть несколько. В пользовательском коде, который не готов, что их несколько, просто поставьте заглушку...

```
const auto polygons = map.polygons();
VERIFY(polygons.size() == 1);
const auto polygon = polygons.size();
```

2023-12-10 01:18 UTC, dasimagin commented on packages/map/src/map_builder.cpp
> +            .get<std::vector<std::vector<std::pair<double, double>>>>();
Я бы лучше чуть больше код написал руками и сразу делал вектора... и тогда конструктор из пары скорее не нужен ¯\_(ツ)_/¯

**P.S.** Почему не юзайте `for-each`? Код станет более компактным.

2023-12-10 01:18 UTC, dasimagin commented on packages/map/package.xml
> +  <license>TODO: License declaration</license>
MIT

2023-12-10 01:18 UTC, dasimagin commented on packages/map/package.xml
> +  <description>TODO: Package description</description>
Я просто пишу название пакета последнее время в этом месте )

2023-12-10 01:18 UTC, dasimagin commented on packages/geom/include/geom/polygon.h
> +    Polygon(const std::vector<Vec2>& vertices) : vertices(vertices) {}
В целом еще можно move-конструктор сделать... а еще для простоты сделайте тупо

`Polygon = std::vector<geom::Vec2>`

2023-12-10 01:18 UTC, dasimagin commented on packages/geom/include/geom/polygon.h
> +    }
Выкинуть ;)

2023-12-10 01:18 UTC, dasimagin commented on packages/geom/include/geom/polygon.h
> +    std::vector<Vec2> vertices;
Это название плохое, так никто не пишет, это `points`.

2023-12-10 01:18 UTC, dasimagin commented on packages/geom/include/geom/complex_polygon.h
> +    }
Давайте выкинем это все...

2023-12-10 01:18 UTC, dasimagin commented on packages/geom/include/geom/complex_polygon.h
> +        : outer_poly(outer_poly), inner_polys(inner_polys) {}
Вот это мне нравится... сделайте еще move-конструктор. И консктруторы с копированием и move, которые предполагают, что внутренних рингов нет.

2023-12-10 01:18 UTC, dasimagin commented on packages/visualization/src/visualization_node.h
> +        double map_z_lev_inner_poly = 0.0;
Почему они разные, простите? )

2023-12-10 01:18 UTC, dasimagin commented on packages/visualization/src/visualization_node.cpp
> +        marker.points.push_back(geom::msg::toPoint(poly.vertices[i + 1]));
Это вы типа так триангуляцию сделали? Это не работает для невыпуклых многоугольников... ¯\_(ツ)_/¯ покажите мне дымку в невыпуклым многоугольником. Было бы здорово в пиар такие картиночки прикладывать, кстати :)

2023-12-10 01:18 UTC, dasimagin commented on packages/visualization/src/visualization_node.cpp
> +    marker.lifetime = rclcpp::Duration::from_seconds(0);
Там и так будет нолик...

2023-12-11 12:12 UTC, andrew-milko commented
> Давайте еще раз уточню... мы все храним в стиле GeoJSON, но при этом хотим работать в метрах. Двигаться в сторону `lat,lon` не будем, чтобы удобно орудовать вьером? :)

Не вижу сейчас смысла переходить от метров к `lat, lon`, т.к.: 1) мы пока что перемещаемся в пространстве малой площади, 2) не нужно тратить время и силы на написание парсера из метров в `lat, lon` для визуализации полигонов карты в виде маркеров

2023-12-11 12:18 UTC, andrew-milko commented on packages/visualization/src/visualization_node.cpp
> +        marker.points.push_back(geom::msg::toPoint(poly.vertices[i + 1]));
> Это вы типа так триангуляцию сделали? Это не работает для невыпуклых многоугольников... ¯_(ツ)_/¯ покажите мне дымку в невыпуклым многоугольником. Было бы здорово в пиар такие картиночки прикладывать, кстати :)

Да, почему для выпуклых это неработает озознал и убедился в этом при попытке отрисовать карту с невыпуклыми полигонами, пример:

![Screenshot-1 png](https://github.com/robotics-laboratory/truck/assets/80720287/75a5d9fa-0b4c-481c-837c-077197c8083f)

Отрисовка, разумеется, некорректная, потому что ожидаем мы вот такую картинку:

![Screenshot from 2023-12-11 15-17-48](https://github.com/robotics-laboratory/truck/assets/80720287/83db0812-dbd6-4270-bec6-1dab277d90d3)

2023-12-16 12:49 UTC, andrew-milko commented on packages/visualization/src/visualization_node.cpp
> +        marker.points.push_back(geom::msg::toPoint(poly.vertices[i + 1]));
Исправлено:

![image](https://github.com/robotics-laboratory/truck/assets/80720287/2ed187f5-2878-4a28-ae9d-a92e4f20a3f6)

2023-12-16 12:54 UTC, andrew-milko commented on packages/visualization/src/visualization_node.h
> +        double map_z_lev_inner_poly = 0.0;
> Почему они разные, простите? )

И правда, два не нужно. Тем более мы не планируем отдельными маркерами отрисовывать дырки. Заменил эти 2 параметра на один новый, `map_z_level`.

2023-12-16 13:58 UTC, andrew-milko commented on packages/map/include/map/map_builder.h
> +    std::string path_;
> В чем смысл затем хранить это поле? Где оно нужно?

Смысла хранить поле `path_` действительно нету.

2023-12-16 14:51 UTC, andrew-milko commented on packages/geom/include/geom/polygon.h
> +    Polygon(const std::vector<Vec2>& vertices) : vertices(vertices) {}
> ... а еще для простоты сделайте тупо `Polygon = std::vector<geom::Vec2>`

Мне такое решение не очень нравится, т.к. у сущности `Polygon` просто помимо набора точек много разных полезных методов может быть. Например уже сейчас я добавил функцию `triangles()`, которая делает триангуляцию для полигона и возвращает список этих треугольников.

Немного погодя может понадобится функция `insidePoint`, которая будет проверять, находится ли указанная точка внутри полигона.

То есть, все-такие есть смысл создавать полноценную структуру под сущность `Polygon`.

2023-12-16 16:35 UTC, andrew-milko commented on packages/map/include/map/map_builder.h
> +class Map {
> При этом мы сразу делаем задел, что их может быть несколько. В пользовательском коде, который не готов, что их несколько, просто поставьте заглушку...

С этим согласен, идея отличная.

2023-12-16 16:37 UTC, andrew-milko commented on packages/map/include/map/map_builder.h
> +class Map {
> Давайте все же чуточку аккуратнее сделаем... Надо стараться не делать тяжелых операций в конструкторе, это больше про инициалзацию ресурсов. Я бы так предложил написать.

Я переделал класс `Map` под ваш манер, но не уеврен, что сделал всё именно так, как вы сказали

Что касается строчки `using ComplexPolygons = std::vector<ComplexPolygon>;`, то она уже написана внутри пакета `geom/complex_polygon.h`, что логично. Не вижу смыслв делать этот `using` внутри пакета `map/include/map_builder.h`

2023-12-16 16:46 UTC, andrew-milko commented on packages/map/src/map_builder.cpp
> +            .get<std::vector<std::vector<std::pair<double, double>>>>();
> Почему не юзайте `for-each`? Код станет более компактным.

Перешел на `for-each`.

2023-12-16 16:46 UTC, andrew-milko commented on packages/map/src/map_builder.cpp
> +            .get<std::vector<std::vector<std::pair<double, double>>>>();
> Я бы лучше чуть больше код написал руками и сразу делал вектора... и тогда конструктор из пары скорее не нужен ¯_(ツ)_/¯

Переписал эту часть.

2023-12-16 17:36 UTC, andrew-milko commented on packages/geom/src/complex_polygon.cpp
Делал триангуляцию по [примеру](https://doc.cgal.org/latest/Triangulation_2/index.html#Subsection_2D_Triangulations_Polygon_triangulation).

2023-12-16 17:36 UTC, andrew-milko commented on packages/geom/src/polygon.cpp
Делал триангуляцию по [примеру](https://doc.cgal.org/latest/Triangulation_2/index.html#Subsection_2D_Triangulations_Polygon_triangulation).

2023-12-16 17:40 UTC, andrew-milko commented on packages/map/data/map_6.geojson
Новая карта с невыпуклыми полигонами.

2023-12-19 22:08 UTC, dasimagin commented
> > Давайте еще раз уточню... мы все храним в стиле GeoJSON, но при этом хотим работать в метрах. Двигаться в сторону `lat,lon` не будем, чтобы удобно орудовать вьером? :)
> 
> Не вижу сейчас смысла переходить от метров к `lat, lon`, т.к.: 1) мы пока что перемещаемся в пространстве малой площади, 2) не нужно тратить время и силы на написание парсера из метров в `lat, lon` для визуализации полигонов карты в виде маркеров

Там только беда с viewer-ами получается, т.к. по стандарту они все ожидают, что мы в `lat/lon` все храним... давайте пока забьем.

2023-12-20 16:27 UTC, dasimagin approved these changes

2023-12-20 16:27 UTC, dasimagin commented on packages/geom/src/polygon.cpp
> +#include <boost/property_map/property_map.hpp>
Не увидел этого в `CMakeLists.txt`.

2023-12-20 16:27 UTC, dasimagin commented on packages/geom/src/complex_polygon.cpp
> +            );
`emplace_back`? В целом это прям многих стрчоку тут касается...

2023-12-20 16:27 UTC, dasimagin commented on packages/map/CMakeLists.txt
> +find_package(nlohmann_json REQUIRED)
Не люблю я эту либку... медленная она, но тут один раз карту читаем, норм.

2023-12-20 16:27 UTC, dasimagin commented on packages/map/CMakeLists.txt
> +    RUNTIME DESTINATION bin
Не вижу, чтобы папку с картами заинсталили...

2023-12-20 16:27 UTC, dasimagin commented on packages/map/include/map/map_builder.h
> +    Map(const geom::ComplexPolygons& polygons);
```
Map(geom::ComplexPolygons polygons): polygons(std::move(polygons)) {}
```

2023-12-20 16:27 UTC, dasimagin commented on packages/map/src/map_builder.cpp
> +            .get<std::vector<std::vector<std::pair<double, double>>>>();
Скорее всего вы там по 3 раза память так скопируете, я бы прошелся явно, но можно забить пока.

2023-12-20 16:27 UTC, dasimagin commented on packages/map/src/map_builder.cpp
> +        for (const auto& points_list : polys_list) {
Логичнее уже тогда ```for(size_t i = 0; ...; ++i)```

2023-12-20 16:27 UTC, dasimagin commented on packages/map/src/map_builder.cpp
> +        polygons.push_back(geom::ComplexPolygon(outer_poly, inner_polys));
Почитайте про `move` и не делайте копий.

2023-12-20 16:27 UTC, dasimagin commented on packages/visualization/src/visualization_node.cpp
> +    msg.color = color::gray(1.0);
Можно даже прозрачненьким...

2023-12-26 12:20 UTC, merged