"NavMesh" Library
robotics-laboratory/truck pull request #95
Opened 2023-12-19 12:21 UTC by andrew-milko

2024-01-02 00:53 UTC, dasimagin commented
1. Учитесь по-тихоньку заполнять `description` пиара.
2. У вас снова стали картинки в репо проползать.

2024-01-02 01:20 UTC, dasimagin approved these changes

2024-01-02 01:20 UTC, dasimagin commented on packages/nav_mesh/include/nav_mesh/nav_mesh.h
> +class NavMesh {
Стремление сделать попроще и написать поменьше кода заставило вас сделать комбайн, который одновременно является мешом, его строителем и рисователем. Все эти 3 сущности лучше бы разделить тогда... это упростит последующее тестирование. К примеру, сейчас нет удобного способа задать меш "руками", можно это делать только через билдер. С другой стороны runtime коду не нужно ничего знать про рисование, это нужно только для отладки.

1. Давайте начнем со строителя... кажется, абсолютно stateless штуковина, удобно это сделать в виде отдельной функии..

```
BuildResult BuildNavMesh(const NavMeshParams& params, const geom::ComplexPolygons& polygons);
```

2. Обратите внимание, я предлагаю возвращать именно структуру... почему так? Если мы хотим теститровать билдер и рисовать его промежуточные варианты, то неплохо бы иметь еще линии уровня и сам скелет, их можно добавить в вовзращаемые рельтат построения.

```
struct BuildResult {
   NavMesh nav_mesh;
   XXX level_lines;
   XXX skeleton;
};
```

Типы, как хранить скелетон и т.п. предложите сами :)

3. Соответственно, если билдер вернул всю информацию таким подробным способом, то можно ее порисовать. Все рисование точно стоит отделить в отдельный файлик (на практике даже делают отдельную либку, но тут можно забить).

2024-01-02 01:20 UTC, dasimagin commented on packages/nav_mesh/include/nav_mesh/nav_mesh.h
> +    const std::vector<geom::Vec2>& mesh() const;
Скорее всего вам понадобиться что-то более сложное, чем массив точек, к примеру, нужно знать ребра между ними? Но это можно отложить до этапа поиска глобального маршрута.

2024-01-02 01:20 UTC, dasimagin commented on packages/nav_mesh/include/nav_mesh/nav_mesh.h
> +#include <opencv2/imgproc.hpp>
Скорее всего это все можно унести в `.cpp`, если аккуратно огранизовать код.

2024-01-02 01:20 UTC, dasimagin commented on packages/nav_mesh/include/nav_mesh/nav_mesh.h
> +    } show;
Есть еще хорошее слово `enable`, но тут на ваш вкус )

2024-01-02 01:20 UTC, dasimagin commented on packages/nav_mesh/include/nav_mesh/nav_mesh.h
> +    } size;
Немного странная штуковина..

2024-01-02 01:20 UTC, dasimagin commented on packages/nav_mesh/src/nav_mesh.cpp
> +    else { cv::polylines(frame, cv_points, 1, color); }
Применяйте `.clang-format`, готовые настройки есть в репо.

2024-01-02 01:21 UTC, dasimagin requested changes
Я набросал там комментарии, исправляйте, жду новую итерацию.

2024-01-03 15:45 UTC, andrew-milko commented on packages/nav_mesh/include/nav_mesh/nav_mesh.h
> +class NavMesh {
> 1. Давайте начнем со строителя... кажется, абсолютно stateless штуковина, удобно это сделать в виде отдельной функии..

Мне показалось, что правильнее было бы задавать параметры меша и полигоны внутри конструра будущего класса `NavMeshBuilder` и сделать отдельную функцию, задача которой просто вернуть уже собранную структурку.

2024-01-06 21:37 UTC, dasimagin approved these changes

2024-01-06 21:37 UTC, dasimagin commented on packages/nav_mesh/include/nav_mesh/nav_mesh_builder.h
> +    NavMeshAttrs attrs_;
Зачем это хранить внутри? Не стесняйтесь передавать в приватных методах.

2024-01-06 21:37 UTC, dasimagin commented on packages/nav_mesh/include/nav_mesh/nav_mesh_builder.h
> +    const NavMeshAttrs& attrs() const;
Скорее это так должно быть...

```
struct NavMeshBuilder {
  NavMeshBuilder(const NavMeshParams& params);
  
  NavMeshAttrs build(const geom::ComplexPolygons& polygons) const;

  // other code...
};
```

2024-01-06 21:37 UTC, dasimagin commented on packages/nav_mesh/include/nav_mesh/nav_mesh_builder.h
> +struct NavMeshAttrs {
Немного странно названо, мб лучше `NavMeshBuild`?

2024-01-07 09:23 UTC, merged